# Generated by Django 6.0.4 on 2026-06-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mannesi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallicenseplate",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="LicensePlate",
        ),
        migrations.DeleteModel(
            name="HistoricalLicensePlate",
        ),
    ]
