# Generated by Django 6.0.4 on 2026-06-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mannesi", "0002_remove_historicallicenseplate_history_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalproductioncredit",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Acconto squadre",
                "verbose_name_plural": "historical Acconti squadre",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalworkhour",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Ore squadre",
                "verbose_name_plural": "historical Ore squadre",
            },
        ),
        migrations.AlterModelOptions(
            name="productioncredit",
            options={
                "ordering": ["-date", "id"],
                "verbose_name": "Acconto squadre",
                "verbose_name_plural": "Acconti squadre",
            },
        ),
        migrations.AlterModelOptions(
            name="workhour",
            options={
                "ordering": ["-date", "id"],
                "verbose_name": "Ore squadre",
                "verbose_name_plural": "Ore squadre",
            },
        ),
    ]
