"""Serve the Ipso offline PWA from the Abies origin."""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from datetime import date as date_type, timezone
from decimal import Decimal
from pathlib import Path

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles import finders
from django.db import IntegrityError, transaction
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.utils import timezone as django_timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST

from apps.base.auth import require_writer
from apps.base.http import (
    CACHE_NO_CACHE, CACHE_NO_STORE, apply_cache_control,
    conditional_file_response,
)
from apps.base.models import (
    HYPSO_FUNC_LN, HarvestPlanItem, HarvestPlanItemState, HypsoParam,
    HypsoParamSet, Parcel, SampleArea, Species, Survey, TreePreserved,
    natural_sort_key, parcel_sort_key,
)
from apps.base.numparse import coord_float, to_decimal
from apps.ipso.models import IpsoUpload, IpsoUploadState
from apps.piano_di_taglio.mark_import import (
    MarkImportRow, import_mark_rows, ipso_mark_fingerprint,
)
from config import strings as S
from config.constants import (
    COLUMNS, DETAIL, DUPLICATE, ERROR, FIELD_ACC_M, FIELD_DAMAGED,
    FIELD_CLIENT_RECORD_ID, FIELD_COMPLETED_AT, FIELD_CREATED_AT,
    FIELD_CSV_TEXT, FIELD_DATE,
    FIELD_D_CM, FIELD_HARVEST_PLAN_ITEM_ID, FIELD_H_M, FIELD_H_MEASURED,
    FIELD_HYPSO_PARAM_SET_ID, FIELD_LAT, FIELD_LON, FIELD_MODE, FIELD_NUMBER,
    FIELD_OPERATOR, FIELD_PARCEL_ID, FIELD_REFERENCE_VERSION,
    FIELD_REGION_ID, FIELD_SCHEMA_VERSION, FIELD_SESSION_ID, FIELD_SPECIES_ID,
    FIELD_STATE, FIELD_WORK_PACKAGE_ID, FILE_ERROR, IMPORTED, IPSO_ERROR_AUTH,
    IPSO_ERROR_CONFLICT, IPSO_ERROR_INVALID_PAYLOAD, IPSO_MODE_MARTELLATE,
    IPSO_MODE_PAI, IPSO_MODE_SAMPLES, IPSO_REFERENCE_JSON, IPSO_TARGET_HARVEST_PLAN_ITEM,
    IPSO_TERRENI_GEOJSON, IPSO_UPLOAD_CONFIG_JS, IPSO_UPLOAD_FILE_CSV,
    IPSO_UPLOAD_FILE_JSON, IPSO_UPLOAD_FILE_SHA256, IPSO_UPLOAD_MODES, MESSAGE, OK,
    PENDING_COUNT, RECORD_COUNT, RECORDS, ROW_ID, ROWS, SESSION, SKIPPED_DUPLICATES, STORED_AS,
    SUGGESTED_TARGET_ID, TARGETS, UPLOAD,
)

SCHEMA_VERSION = 1
UPLOAD_SCHEMA_VERSION = 1
ALLOWED_UPLOAD_MODES = set(IPSO_UPLOAD_MODES)

ASSET_CONTENT_TYPES = {
    '.css': 'text/css; charset=utf-8',
    '.gif': 'image/gif',
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.png': 'image/png',
    '.webmanifest': 'application/manifest+json',
}

ASSET_FILES = {
    'app.js',
    'csv.js',
    'download.js',
    'geo.js',
    'gps.js',
    'index.html',
    'ipso.js',
    'manifest.webmanifest',
    'map.js',
    'modes.js',
    'numpad.js',
    'parcel-locator.js',
    'session.js',
    'store.js',
    'strings.js',
    'style.css',
    'sw.js',
    'upload.js',
    'version.js',
    'img/f.gif',
    'img/l.gif',
    'img/icon-192.png',
    'img/icon-512.png',
    'img/icon-512-maskable.png',
}

_DATE_RE = re.compile(r'^\d{4}-\d{2}-\d{2}$')
_SESSION_ID_RE = re.compile(
    r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
    r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
)


class UploadValidationError(ValueError):
    pass


@require_GET
def index(request: HttpRequest) -> HttpResponse:
    return _asset_response(request, 'index.html')


@require_GET
def upload_config_js(request: HttpRequest) -> HttpResponse:
    token = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    response = HttpResponse(
        '// Generated by Abies. Do not edit.\n'
        "'use strict';\n"
        f'const UPLOAD_TOKEN = {json.dumps(token)};\n',
        content_type='text/javascript; charset=utf-8',
    )
    apply_cache_control(response, CACHE_NO_STORE)
    return response


@require_GET
def asset(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path in {IPSO_REFERENCE_JSON, IPSO_TERRENI_GEOJSON, IPSO_UPLOAD_CONFIG_JS}:
        raise Http404
    return _asset_response(request, asset_path)


def _asset_response(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path not in ASSET_FILES:
        raise Http404
    path = _static_path(asset_path)
    content_type = ASSET_CONTENT_TYPES.get(Path(asset_path).suffix)
    if content_type is None:
        raise Http404
    return conditional_file_response(
        request, path, content_type=content_type, cache_control=CACHE_NO_CACHE,
    )


def _static_path(asset_path: str) -> Path:
    found = finders.find(f'ipso/{asset_path}')
    if not found:
        raise Http404
    return Path(found)


@require_GET
def reference_json(request: HttpRequest) -> HttpResponse:
    """Current-client reference bundle, generated from Abies data.

    The existing Ipso UI still consumes the legacy display fields
    (`common`, `compresa`, `particella`) while the integrated upload path uses
    the added canonical Abies IDs (`id`, `region_id`, `parcel_id`).
    """
    sampling = _sampling_context()
    pai = _pai_context()
    payload = {
        FIELD_SCHEMA_VERSION: SCHEMA_VERSION,
        'generated_at': django_timezone.now().astimezone(timezone.utc)
                       .isoformat(timespec='seconds').replace('+00:00', 'Z'),
        'species': _species_rows(),
        'parcels': _parcel_rows(),
        'ipsometrica': _ipsometrica(),
        'sampling': sampling,
        'pai': pai,
        'work_packages': _work_packages(sampling),
    }
    payload[FIELD_REFERENCE_VERSION] = _reference_version(payload)
    return _json_response(payload, content_type='application/json')


def _species_rows() -> list[dict]:
    return [
        {
            'id': sp.id,
            'common': sp.common_name,
            'latin': sp.latin_name,
            'sort_order': sp.sort_order,
            'density': float(sp.density),
        }
        for sp in Species.objects.filter(active=True).order_by('sort_order', 'common_name')
    ]


def _parcel_rows() -> list[dict]:
    parcels = sorted(
        Parcel.objects.select_related('region', 'eclass').filter(eclass__coppice=False),
        key=parcel_sort_key,
    )
    return [
        {
            FIELD_REGION_ID: p.region_id,
            'region_name': p.region.name,
            FIELD_PARCEL_ID: p.id,
            'compresa': p.region.name,
            'particella': p.name,
        }
        for p in parcels
    ]


def _sampling_context() -> dict:
    surveys = list(
        Survey.objects
        .filter(active=True)
        .select_related('sample_grid')
        .order_by('name', 'id')
    )
    grid_ids = {s.sample_grid_id for s in surveys}
    areas = []
    if grid_ids:
        areas = list(
            SampleArea.objects
            .filter(sample_grid_id__in=grid_ids)
            .select_related('sample_grid', 'parcel__region')
        )
        areas.sort(key=lambda a: (
            a.sample_grid.name, parcel_sort_key(a.parcel),
            natural_sort_key(a.number), a.id,
        ))
    return {
        'surveys': [
            {
                'survey_id': s.id,
                'name': s.name,
                'sample_grid_id': s.sample_grid_id,
                'sample_grid_name': s.sample_grid.name,
            }
            for s in surveys
        ],
        'sample_areas': [
            {
                'sample_area_id': a.id,
                'sample_grid_id': a.sample_grid_id,
                FIELD_REGION_ID: a.parcel.region_id,
                FIELD_PARCEL_ID: a.parcel_id,
                'compresa': a.parcel.region.name,
                'particella': a.parcel.name,
                FIELD_NUMBER: a.number,
                FIELD_LAT: a.lat,
                FIELD_LON: a.lon,
                'r_m': a.r_m,
            }
            for a in areas
        ],
    }


def _pai_context() -> dict:
    rows = (
        TreePreserved.objects
        .select_related('tree__species', 'parcel__region')
        .order_by('parcel__region__name', 'parcel__name', FIELD_NUMBER, 'id')
    )
    return {
        'preserved_trees': [
            {
                'tree_preserved_id': p.id,
                'tree_id': p.tree_id,
                FIELD_REGION_ID: p.parcel.region_id,
                FIELD_PARCEL_ID: p.parcel_id,
                'compresa': p.parcel.region.name,
                'particella': p.parcel.name,
                FIELD_SPECIES_ID: p.tree.species_id,
                FIELD_NUMBER: p.number,
                'estimated_birth_year': p.tree.estimated_birth_year,
                FIELD_DATE: p.date.isoformat() if p.date else '',
                FIELD_D_CM: p.d_cm,
                FIELD_H_M: str(p.h_m) if p.h_m is not None else None,
                FIELD_H_MEASURED: p.h_measured,
                FIELD_LAT: p.lat,
                FIELD_LON: p.lon,
                FIELD_ACC_M: p.acc_m,
                FIELD_OPERATOR: p.operator,
                'note': p.note,
            }
            for p in rows
        ],
    }


def _work_packages(sampling: dict) -> list[dict]:
    return [
        {
            'id': f"sampling_survey:{s['survey_id']}",
            'kind': 'sampling_survey',
            'label': s['name'],
            'survey_id': s['survey_id'],
            'sample_grid_id': s['sample_grid_id'],
        }
        for s in sampling['surveys']
    ]


def _ipsometrica() -> dict:
    active = HypsoParamSet.objects.active().first()
    if active is None:
        return {}
    out: dict[str, dict[str, dict[str, float]]] = {}
    params = (HypsoParam.objects
              .filter(param_set=active, func=HYPSO_FUNC_LN)
              .select_related('region', 'species')
              .order_by('region__name', 'species__common_name'))
    for p in params:
        out.setdefault(p.region.name, {})[p.species.common_name] = {
            'a': float(p.a),
            'b': float(p.b),
            FIELD_HYPSO_PARAM_SET_ID: active.id,
        }
    return out


def _reference_version(payload: dict) -> str:
    raw = json.dumps({
        'species': payload['species'],
        'parcels': payload['parcels'],
        'ipsometrica': payload['ipsometrica'],
        'sampling': payload['sampling'],
        'pai': payload['pai'],
        'work_packages': payload['work_packages'],
    }, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()[:20]


@require_GET
def terreni_geojson(request: HttpRequest) -> HttpResponse:
    path = Path(settings.GEO_DIR) / IPSO_TERRENI_GEOJSON
    if path.is_file():
        return conditional_file_response(
            request, path, content_type='application/geo+json',
            cache_control=CACHE_NO_CACHE,
        )
    return _json_response(
        {'type': 'FeatureCollection', 'features': []},
        content_type='application/geo+json', cache_control=CACHE_NO_CACHE,
    )


INBOX_COLUMNS = [
    ROW_ID, S.IPSO_COL_RECEIVED, S.IPSO_COL_MODE, S.IPSO_COL_OPERATOR,
    S.IPSO_COL_RECORDS, S.IPSO_COL_STATE, S.IPSO_COL_WORK_PACKAGE,
    S.IPSO_COL_TARGET, S.IPSO_COL_ERROR,
]
STATE_LABELS = {
    IpsoUploadState.RECEIVED: S.IPSO_STATE_RECEIVED,
    IpsoUploadState.IMPORTED: S.IPSO_STATE_IMPORTED,
    IpsoUploadState.REJECTED: S.IPSO_STATE_REJECTED,
    IpsoUploadState.CONFLICT: S.IPSO_STATE_CONFLICT,
}


@login_required
@require_GET
def inbox_data(request: HttpRequest) -> JsonResponse:
    uploads = IpsoUpload.objects.order_by('-received_at')
    payload = {
        COLUMNS: INBOX_COLUMNS,
        ROWS: [_inbox_row(u) for u in uploads],
        PENDING_COUNT: uploads.filter(state=IpsoUploadState.RECEIVED).count(),
    }
    return _api_json(payload)


@login_required
@require_GET
def upload_detail(request: HttpRequest, upload_id: int) -> JsonResponse:
    upload = _get_upload(upload_id)
    payload, file_error = _read_staged_payload(upload)
    session = payload.get(SESSION, {}) if payload else {}
    records = payload.get(RECORDS, []) if payload else []
    return _api_json({
        UPLOAD: _upload_metadata(upload),
        SESSION: session,
        RECORDS: _preview_records(records),
        RECORD_COUNT: len(records),
        FILE_ERROR: file_error,
        TARGETS: _martellate_targets(),
        SUGGESTED_TARGET_ID: _suggested_harvest_item_id(upload.work_package_id),
    })


@login_required
@require_writer
@require_POST
def reject_upload(request: HttpRequest, upload_id: int) -> JsonResponse:
    with transaction.atomic():
        upload = _get_upload(upload_id, for_update=True)
        if upload.state == IpsoUploadState.IMPORTED:
            return _api_json({
                OK: False,
                MESSAGE: S.IPSO_ERR_IMPORTED_CANNOT_REJECT,
            }, status=400)
        reason = _reject_reason(request)
        updated = (IpsoUpload.objects
                   .filter(id=upload.id)
                   .exclude(state=IpsoUploadState.IMPORTED)
                   .update(state=IpsoUploadState.REJECTED, error_summary=reason))
        if not updated:
            return _api_json({
                OK: False,
                MESSAGE: S.IPSO_ERR_IMPORTED_CANNOT_REJECT,
            }, status=400)
        upload.state = IpsoUploadState.REJECTED
        upload.error_summary = reason
        data = _upload_metadata(upload)
    return _api_json({OK: True, UPLOAD: data})


@login_required
@require_writer
@require_POST
def import_martellate_upload(request: HttpRequest, upload_id: int) -> JsonResponse:
    try:
        body = _request_json(request)
        item_id = _int(body, FIELD_HARVEST_PLAN_ITEM_ID)
    except UploadValidationError as e:
        return _api_json({OK: False, MESSAGE: str(e)}, status=400)

    with transaction.atomic():
        upload = _get_upload(upload_id, for_update=True)
        if upload.mode != IPSO_MODE_MARTELLATE:
            return _api_json({OK: False, MESSAGE: S.IPSO_ERR_MODE_UNSUPPORTED}, status=400)
        if upload.state != IpsoUploadState.RECEIVED:
            return _api_json({
                OK: False,
                MESSAGE: S.IPSO_ERR_UPLOAD_NOT_RECEIVED,
            }, status=400)
        item = (HarvestPlanItem.objects
                .select_for_update()
                .filter(id=item_id).first())
        if item is None:
            return _api_json({OK: False, MESSAGE: S.ERR_PLAN_ITEM_NOT_FOUND}, status=400)
        if item.state == HarvestPlanItemState.CLOSED:
            return _api_json({OK: False, MESSAGE: S.ERR_MARK_ITEM_CLOSED}, status=400)
        if not _is_valid_martellate_target(item):
            return _api_json({
                OK: False,
                MESSAGE: S.IPSO_ERR_INVALID_MARTELLATE_TARGET,
            }, status=400)

        payload, file_error = _read_staged_payload(upload)
        if file_error:
            return _api_json({OK: False, MESSAGE: file_error}, status=400)
        rows, errors = _martellate_import_rows(upload, payload, item)
        if errors:
            return _api_json({OK: False, MESSAGE: '\n'.join(errors), 'errors': errors}, status=400)

        imported_at = django_timezone.now()
        claimed = (IpsoUpload.objects
                   .filter(id=upload.id, state=IpsoUploadState.RECEIVED)
                   .update(
                       state=IpsoUploadState.IMPORTED,
                       imported_at=imported_at,
                       imported_by_id=request.user.id,
                       target_type=IPSO_TARGET_HARVEST_PLAN_ITEM,
                       target_id=item.id,
                       error_summary='',
                   ))
        if not claimed:
            return _api_json({
                OK: False,
                MESSAGE: S.IPSO_ERR_UPLOAD_NOT_RECEIVED,
            }, status=400)
        upload.state = IpsoUploadState.IMPORTED
        upload.imported_at = imported_at
        upload.imported_by = request.user
        upload.target_type = IPSO_TARGET_HARVEST_PLAN_ITEM
        upload.target_id = item.id
        upload.error_summary = ''
        result = import_mark_rows(item, rows)
        data = _upload_metadata(upload)
    return _api_json({
        OK: True,
        IMPORTED: result.imported,
        SKIPPED_DUPLICATES: result.skipped_duplicates,
        UPLOAD: data,
    })


@csrf_exempt
@require_POST
def upload_session(request: HttpRequest) -> JsonResponse:
    if not _upload_authorized(request):
        return _api_json({OK: False, ERROR: IPSO_ERROR_AUTH}, status=401)
    try:
        payload = _request_json(request)
        normalized, csv_text = _validate_upload_payload(payload, request)
    except UploadValidationError as e:
        return _api_json({OK: False, ERROR: IPSO_ERROR_INVALID_PAYLOAD, DETAIL: str(e)}, status=422)

    checksum = _payload_checksum(normalized)
    session_id = normalized[SESSION][FIELD_SESSION_ID]
    try:
        with transaction.atomic():
            inbox_path = _upload_inbox_path(session_id)
            upload = IpsoUpload.objects.create(
                session_id=session_id,
                mode=normalized[SESSION][FIELD_MODE],
                schema_version=normalized[SESSION][FIELD_SCHEMA_VERSION],
                reference_version=normalized[SESSION].get(FIELD_REFERENCE_VERSION, ''),
                work_package_id=normalized[SESSION].get(FIELD_WORK_PACKAGE_ID, ''),
                operator=normalized[SESSION].get(FIELD_OPERATOR, ''),
                record_count=len(normalized[RECORDS]),
                checksum=checksum,
                inbox_path=str(inbox_path),
            )
            _write_upload_files(inbox_path, normalized, checksum, csv_text)
    except IntegrityError:
        return _duplicate_upload_response(session_id, checksum)

    return _api_json({
        OK: True,
        STORED_AS: upload.inbox_path,
        DUPLICATE: False,
    })


def _duplicate_upload_response(session_id: str, checksum: str) -> JsonResponse:
    existing = IpsoUpload.objects.filter(session_id=session_id).first()
    if existing is None:
        return _api_json({OK: False, ERROR: IPSO_ERROR_CONFLICT}, status=409)
    if hmac.compare_digest(existing.checksum, checksum):
        return _api_json({
            OK: True,
            STORED_AS: existing.inbox_path,
            DUPLICATE: True,
        })
    existing.state = IpsoUploadState.CONFLICT
    existing.error_summary = S.IPSO_ERR_DUPLICATE_SESSION_CONTENT
    existing.save(update_fields=['state', 'error_summary'])
    return _api_json({OK: False, ERROR: IPSO_ERROR_CONFLICT}, status=409)


def _get_upload(upload_id: int, *, for_update: bool = False) -> IpsoUpload:
    qs = IpsoUpload.objects
    if for_update:
        qs = qs.select_for_update()
    try:
        return qs.get(id=upload_id)
    except IpsoUpload.DoesNotExist as e:
        raise Http404 from e


def _inbox_row(upload: IpsoUpload) -> list:
    return [
        upload.id,
        _format_dt(upload.received_at),
        upload.mode,
        upload.operator,
        upload.record_count,
        STATE_LABELS.get(upload.state, upload.state),
        upload.work_package_id,
        _target_label(upload),
        upload.error_summary,
    ]


def _upload_metadata(upload: IpsoUpload) -> dict:
    return {
        'id': upload.id,
        FIELD_SESSION_ID: upload.session_id,
        FIELD_MODE: upload.mode,
        FIELD_SCHEMA_VERSION: upload.schema_version,
        FIELD_REFERENCE_VERSION: upload.reference_version,
        FIELD_WORK_PACKAGE_ID: upload.work_package_id,
        FIELD_OPERATOR: upload.operator,
        RECORD_COUNT: upload.record_count,
        'checksum': upload.checksum,
        FIELD_STATE: upload.state,
        'state_label': STATE_LABELS.get(upload.state, upload.state),
        'received_at': _format_dt(upload.received_at),
        'imported_at': _format_dt(upload.imported_at),
        'target_type': upload.target_type,
        'target_id': upload.target_id,
        'target_label': _target_label(upload),
        'error_summary': upload.error_summary,
    }


def _target_label(upload: IpsoUpload) -> str:
    if upload.target_type == IPSO_TARGET_HARVEST_PLAN_ITEM and upload.target_id:
        item = (HarvestPlanItem.objects
                .select_related('harvest_plan', 'parcel__region', 'parcel__eclass', 'region')
                .filter(id=upload.target_id).first())
        if item is not None:
            return _harvest_item_label(item)
    if upload.target_type and upload.target_id:
        return f'{upload.target_type}:{upload.target_id}'
    return ''


def _format_dt(value) -> str:
    if not value:
        return ''
    return value.astimezone(timezone.utc).strftime('%Y-%m-%d %H:%M')


def _read_staged_payload(upload: IpsoUpload) -> tuple[dict, str]:
    path = Path(upload.inbox_path) / IPSO_UPLOAD_FILE_JSON
    try:
        return json.loads(path.read_text(encoding='utf-8')), ''
    except FileNotFoundError:
        return {}, S.IPSO_ERR_UPLOAD_JSON_MISSING
    except json.JSONDecodeError:
        return {}, S.IPSO_ERR_UPLOAD_JSON_INVALID


def _preview_records(records: list) -> list[dict]:
    if not isinstance(records, list):
        return []
    species_ids = {
        r.get(FIELD_SPECIES_ID) for r in records
        if isinstance(r, dict) and type(r.get(FIELD_SPECIES_ID)) is int
    }
    parcel_ids = {
        r.get(FIELD_PARCEL_ID) for r in records
        if isinstance(r, dict) and type(r.get(FIELD_PARCEL_ID)) is int
    }
    species = {
        sp.id: sp.common_name
        for sp in Species.objects.filter(id__in=species_ids)
    }
    parcels = {
        p.id: f'{p.region.name} {p.name}'
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region')
    }
    out = []
    for i, row in enumerate(records[:500], start=1):
        if not isinstance(row, dict):
            continue
        out.append({
            'seq': row.get(FIELD_CLIENT_RECORD_ID) or str(i),
            FIELD_DATE: row.get(FIELD_DATE, ''),
            'parcel': parcels.get(row.get(FIELD_PARCEL_ID), str(row.get(FIELD_PARCEL_ID, ''))),
            'species': species.get(row.get(FIELD_SPECIES_ID), str(row.get(FIELD_SPECIES_ID, ''))),
            FIELD_NUMBER: row.get(FIELD_NUMBER),
            FIELD_D_CM: row.get(FIELD_D_CM),
            FIELD_H_M: row.get(FIELD_H_M),
            FIELD_H_MEASURED: bool(row.get(FIELD_H_MEASURED)),
            FIELD_LAT: row.get(FIELD_LAT),
            FIELD_LON: row.get(FIELD_LON),
            FIELD_ACC_M: row.get(FIELD_ACC_M),
        })
    return out


def _reject_reason(request: HttpRequest) -> str:
    try:
        body = json.loads(request.body.decode('utf-8') or '{}')
    except (UnicodeDecodeError, json.JSONDecodeError):
        body = {}
    reason = body.get('reason', '') if isinstance(body, dict) else ''
    return reason.strip() or S.IPSO_REJECT_DEFAULT_REASON


def _martellate_targets() -> list[dict]:
    items = (HarvestPlanItem.objects
             .select_related('harvest_plan', 'parcel__region', 'parcel__eclass', 'region')
             .exclude(state=HarvestPlanItemState.CLOSED)
             .order_by('harvest_plan__name', 'year_planned', 'id'))
    out = []
    for item in items:
        if _is_valid_martellate_target(item):
            out.append({'id': item.id, 'label': _harvest_item_label(item)})
    return out


def _is_valid_martellate_target(item: HarvestPlanItem) -> bool:
    if item.state == HarvestPlanItemState.CLOSED:
        return False
    return not (item.parcel_id and item.parcel.eclass.coppice)


def _harvest_item_label(item: HarvestPlanItem) -> str:
    if item.parcel_id:
        area = f'{item.parcel.region.name} {item.parcel.name}'
    elif item.region_id:
        area = item.region.name
    else:
        area = '-'
    state = HarvestPlanItemState(item.state).label
    return f'{item.harvest_plan.name} - {area} - {item.year_planned} ({state})'


def _suggested_harvest_item_id(work_package_id: str) -> int | None:
    raw = (work_package_id or '').strip()
    if raw.startswith('harvest:'):
        raw = raw.split(':', 1)[1]
    if not raw.isdigit():
        return None
    item_id = int(raw)
    item = (HarvestPlanItem.objects
            .select_related('parcel__eclass')
            .filter(id=item_id).first())
    if item is not None and _is_valid_martellate_target(item):
        return item_id
    return None


def _martellate_import_rows(
        upload: IpsoUpload, payload: dict, item: HarvestPlanItem,
) -> tuple[list[MarkImportRow], list[str]]:
    session = payload.get(SESSION, {}) if isinstance(payload, dict) else {}
    records = payload.get(RECORDS, []) if isinstance(payload, dict) else []
    if not isinstance(records, list):
        return [], ['records deve essere un array.']

    species_ids = {
        r.get(FIELD_SPECIES_ID) for r in records
        if isinstance(r, dict) and type(r.get(FIELD_SPECIES_ID)) is int
    }
    parcel_ids = {
        r.get(FIELD_PARCEL_ID) for r in records
        if isinstance(r, dict) and type(r.get(FIELD_PARCEL_ID)) is int
    }
    species = {
        sp.id: sp
        for sp in Species.objects.filter(id__in=species_ids)
    }
    parcels = {
        p.id: p
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region', 'eclass')
    }
    item_region = item.region or (item.parcel.region if item.parcel else None)
    operator = (session.get(FIELD_OPERATOR) or '').strip() if isinstance(session, dict) else ''

    rows = []
    errors = []
    for i, record in enumerate(records, start=1):
        if not isinstance(record, dict):
            errors.append(f'Record {i}: formato non valido.')
            continue
        parcel = parcels.get(record.get(FIELD_PARCEL_ID))
        if parcel is None:
            errors.append(f'Record {i}: particella non trovata.')
            continue
        if item_region and parcel.region_id != item_region.id:
            errors.append(S.ERR_MARK_PARCEL_NOT_IN_REGION)
            continue
        sp = species.get(record.get(FIELD_SPECIES_ID))
        if sp is None:
            errors.append(f'Record {i}: specie non trovata.')
            continue
        try:
            date = date_type.fromisoformat(str(record.get(FIELD_DATE)))
            d_cm = int(record.get(FIELD_D_CM))
            h_m = to_decimal(record.get(FIELD_H_M), '.')
            if h_m is None:
                raise ValueError
        except (TypeError, ValueError):
            errors.append(f'Record {i}: D/H/data non validi.')
            continue
        rows.append(MarkImportRow(
            date=date,
            parcel=parcel,
            species=sp,
            number=record.get(FIELD_NUMBER),
            d_cm=d_cm,
            h_m=h_m,
            h_measured=bool(record.get(FIELD_H_MEASURED)),
            lat=record.get(FIELD_LAT),
            lon=record.get(FIELD_LON),
            acc_m=record.get(FIELD_ACC_M),
            operator=operator,
            fingerprint=ipso_mark_fingerprint(upload.session_id, record),
        ))
    return rows, errors


def _upload_authorized(request: HttpRequest) -> bool:
    expected = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    if not expected:
        return True
    prefix = 'Bearer '
    header = request.headers.get('Authorization', '')
    if not header.startswith(prefix):
        return False
    return hmac.compare_digest(header[len(prefix):], expected)


def _request_json(request: HttpRequest) -> dict:
    try:
        payload = json.loads(request.body.decode('utf-8'))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise UploadValidationError('Malformed JSON.') from e
    if not isinstance(payload, dict):
        raise UploadValidationError('Payload must be an object.')
    return payload


def _validate_upload_payload(payload: dict, request: HttpRequest) -> tuple[dict, str | None]:
    session = _dict(payload, SESSION)
    records = _list(payload, RECORDS)
    csv_text = payload.get(FIELD_CSV_TEXT)
    if csv_text is not None and not isinstance(csv_text, str):
        raise UploadValidationError('csv_text must be a string when present.')

    normalized_session = _normalize_session(session)
    header_id = request.headers.get('X-Ipso-Session-Id', '')
    if header_id and header_id != normalized_session[FIELD_SESSION_ID]:
        raise UploadValidationError('X-Ipso-Session-Id does not match session.session_id.')

    normalized_records = [
        _normalize_record(normalized_session[FIELD_MODE], i, row)
        for i, row in enumerate(records, start=1)
    ]
    _validate_record_ids(normalized_records)
    return {SESSION: normalized_session, RECORDS: normalized_records}, csv_text


def _normalize_session(session: dict) -> dict:
    session_id = _str(session, FIELD_SESSION_ID)
    if not _SESSION_ID_RE.match(session_id):
        raise UploadValidationError('session_id must be a UUID.')
    mode = _str(session, FIELD_MODE)
    if mode not in ALLOWED_UPLOAD_MODES:
        raise UploadValidationError('Unsupported mode.')
    schema_version = _int(session, FIELD_SCHEMA_VERSION)
    if schema_version != UPLOAD_SCHEMA_VERSION:
        raise UploadValidationError('Unsupported schema_version.')
    normalized = {
        FIELD_SESSION_ID: session_id,
        FIELD_MODE: mode,
        FIELD_SCHEMA_VERSION: schema_version,
        FIELD_REFERENCE_VERSION: _opt_str(session, FIELD_REFERENCE_VERSION),
        FIELD_WORK_PACKAGE_ID: _opt_str(session, FIELD_WORK_PACKAGE_ID),
        FIELD_OPERATOR: _opt_str(session, FIELD_OPERATOR),
        FIELD_CREATED_AT: _opt_str(session, FIELD_CREATED_AT),
        FIELD_COMPLETED_AT: _opt_str(session, FIELD_COMPLETED_AT),
        FIELD_DAMAGED: _bool(session, FIELD_DAMAGED),
    }
    region_id = session.get(FIELD_REGION_ID)
    if region_id is not None:
        normalized[FIELD_REGION_ID] = _int(session, FIELD_REGION_ID)
    return normalized


def _normalize_record(mode: str, index: int, row: object) -> dict:
    if not isinstance(row, dict):
        raise UploadValidationError(f'Record {index}: must be an object.')
    date = _str(row, FIELD_DATE)
    if not _DATE_RE.match(date):
        raise UploadValidationError(f'Record {index}: date must be YYYY-MM-DD.')

    d_cm = (
        _opt_int(row, FIELD_D_CM) if mode == IPSO_MODE_PAI
        else _int(row, FIELD_D_CM)
    )
    if d_cm is not None and d_cm <= 0:
        raise UploadValidationError(f'Record {index}: d_cm must be positive.')

    h_m = (
        _opt_decimal(row, FIELD_H_M) if mode == IPSO_MODE_PAI
        else _decimal(row, FIELD_H_M)
    )
    if h_m is not None and h_m <= 0:
        raise UploadValidationError(f'Record {index}: h_m must be positive.')

    hypso_param_set_id = _opt_int(row, FIELD_HYPSO_PARAM_SET_ID)
    if mode != IPSO_MODE_MARTELLATE and hypso_param_set_id is not None:
        raise UploadValidationError(
            f'Record {index}: hypso_param_set_id is only valid for martellate.'
        )

    return {
        FIELD_CLIENT_RECORD_ID: _str(row, FIELD_CLIENT_RECORD_ID),
        FIELD_DATE: date,
        FIELD_REGION_ID: _int(row, FIELD_REGION_ID),
        FIELD_PARCEL_ID: _int(row, FIELD_PARCEL_ID),
        FIELD_SPECIES_ID: _int(row, FIELD_SPECIES_ID),
        FIELD_NUMBER: _opt_int(row, FIELD_NUMBER),
        FIELD_D_CM: d_cm,
        FIELD_H_M: format(h_m, 'f') if h_m is not None else None,
        FIELD_H_MEASURED: _bool(row, FIELD_H_MEASURED),
        FIELD_HYPSO_PARAM_SET_ID: hypso_param_set_id,
        FIELD_LAT: _opt_coord_float(row, FIELD_LAT),
        FIELD_LON: _opt_coord_float(row, FIELD_LON),
        FIELD_ACC_M: _opt_int(row, FIELD_ACC_M),
    }


def _validate_record_ids(records: list[dict]) -> None:
    species_ids = {r[FIELD_SPECIES_ID] for r in records}
    parcel_ids = {r[FIELD_PARCEL_ID] for r in records}
    hypso_ids = {r[FIELD_HYPSO_PARAM_SET_ID] for r in records if r[FIELD_HYPSO_PARAM_SET_ID] is not None}
    valid_species = set(Species.objects.filter(id__in=species_ids).values_list('id', flat=True))
    parcels = {
        p.id: p.region_id
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region')
    }
    missing_species = species_ids - valid_species
    if missing_species:
        raise UploadValidationError(f'Unknown species_id: {min(missing_species)}.')
    missing_parcels = parcel_ids - set(parcels)
    if missing_parcels:
        raise UploadValidationError(f'Unknown parcel_id: {min(missing_parcels)}.')
    valid_hypso = set(HypsoParamSet.objects.filter(id__in=hypso_ids).values_list('id', flat=True))
    missing_hypso = hypso_ids - valid_hypso
    if missing_hypso:
        raise UploadValidationError(f'Unknown hypso_param_set_id: {min(missing_hypso)}.')
    for i, row in enumerate(records, start=1):
        if parcels[row[FIELD_PARCEL_ID]] != row[FIELD_REGION_ID]:
            raise UploadValidationError(f'Record {i}: parcel_id not in region_id.')


def _payload_checksum(payload: dict) -> str:
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


def _upload_inbox_path(session_id: str) -> Path:
    now = django_timezone.now().astimezone(timezone.utc)
    return Path(settings.IPSO_INBOX_DIR) / f'{now.year:04d}' / f'{now.month:02d}' / session_id


def _write_upload_files(
        session_dir: Path, payload: dict, checksum: str, csv_text: str | None,
) -> Path:
    session_dir.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(
        session_dir / IPSO_UPLOAD_FILE_JSON,
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + '\n',
    )
    _atomic_write_text(session_dir / IPSO_UPLOAD_FILE_SHA256, checksum + '\n')
    if csv_text:
        _atomic_write_text(session_dir / IPSO_UPLOAD_FILE_CSV, csv_text)
    return session_dir


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(path)


def _dict(payload: dict, key: str) -> dict:
    value = payload.get(key)
    if not isinstance(value, dict):
        raise UploadValidationError(f'{key} must be an object.')
    return value


def _list(payload: dict, key: str) -> list:
    value = payload.get(key)
    if not isinstance(value, list):
        raise UploadValidationError(f'{key} must be an array.')
    return value


def _str(payload: dict, key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise UploadValidationError(f'{key} is required.')
    return value.strip()


def _opt_str(payload: dict, key: str) -> str:
    value = payload.get(key, '')
    if value is None:
        return ''
    if not isinstance(value, str):
        raise UploadValidationError(f'{key} must be a string.')
    return value.strip()


def _int(payload: dict, key: str) -> int:
    value = payload.get(key)
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer.')
    return value


def _opt_int(payload: dict, key: str) -> int | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer or null.')
    return value


def _bool(payload: dict, key: str) -> bool:
    value = payload.get(key)
    if type(value) is not bool:
        raise UploadValidationError(f'{key} must be a boolean.')
    return value


def _opt_coord_float(payload: dict, key: str) -> float | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) not in {int, float}:
        raise UploadValidationError(f'{key} must be a number or null.')
    out = coord_float(to_decimal(value, '.'))
    if out is None:
        raise UploadValidationError(f'{key} must be finite.')
    return out


def _opt_decimal(payload: dict, key: str) -> Decimal | None:
    value = payload.get(key)
    if value is None:
        return None
    return _decimal(payload, key)


def _decimal(payload: dict, key: str) -> Decimal:
    value = payload.get(key)
    if type(value) not in {int, float, str}:
        raise UploadValidationError(f'{key} must be a decimal value.')
    dec = to_decimal(value, '.')
    if dec is None:
        raise UploadValidationError(f'{key} must be a finite decimal value.')
    return dec


def _json_response(
        payload: dict, *, content_type: str,
        cache_control: str = CACHE_NO_STORE,
) -> HttpResponse:
    response = HttpResponse(
        json.dumps(payload, ensure_ascii=False, separators=(',', ':')),
        content_type=content_type,
    )
    apply_cache_control(response, cache_control)
    return response


def _api_json(payload: dict, *, status: int = 200) -> JsonResponse:
    response = JsonResponse(payload, status=status)
    apply_cache_control(response, CACHE_NO_STORE)
    return response
