"""Serve the Ipso offline PWA from the Abies origin."""

from __future__ import annotations

import hashlib
import hmac
import json
import math
import re
from datetime import date as date_type, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles import finders
from django.db import IntegrityError
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.utils import timezone as django_timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST

from apps.base.auth import require_writer
from apps.base.http import (
    CACHE_NO_CACHE, CACHE_NO_STORE, apply_cache_control,
    conditional_file_response,
)
from apps.base.models import (
    HYPSO_FUNC_LN, HarvestPlanItem, HarvestPlanItemState, HypsoParam,
    HypsoParamSet, Parcel, Species,
)
from apps.ipso.models import IpsoUpload, IpsoUploadState
from apps.piano_di_taglio.mark_import import (
    MarkImportRow, import_mark_rows, ipso_mark_fingerprint,
)
from config import strings as S

SCHEMA_VERSION = 1
UPLOAD_SCHEMA_VERSION = 1
UPLOAD_MODE_MARTELLATE = 'martellate'
TARGET_TYPE_HARVEST_PLAN_ITEM = 'harvest_plan_item'

ASSET_CONTENT_TYPES = {
    '.css': 'text/css; charset=utf-8',
    '.gif': 'image/gif',
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.png': 'image/png',
    '.webmanifest': 'application/manifest+json',
}

ASSET_FILES = {
    'app.js',
    'csv.js',
    'download.js',
    'geo.js',
    'gps.js',
    'index.html',
    'ipso.js',
    'manifest.webmanifest',
    'map.js',
    'modes.js',
    'numpad.js',
    'parcel-locator.js',
    'session.js',
    'store.js',
    'strings.js',
    'style.css',
    'sw.js',
    'upload.js',
    'version.js',
    'img/f.gif',
    'img/l.gif',
    'img/icon-192.png',
    'img/icon-512.png',
    'img/icon-512-maskable.png',
}

_NATKEY_RE = re.compile(r'(\d+)')
_DATE_RE = re.compile(r'^\d{4}-\d{2}-\d{2}$')
_SESSION_ID_RE = re.compile(
    r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
    r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
)


class UploadValidationError(ValueError):
    pass


def _natural_key(value: str) -> list:
    return [int(p) if p.isdigit() else p.lower() for p in _NATKEY_RE.split(value)]


@require_GET
def index(request: HttpRequest) -> HttpResponse:
    return _asset_response(request, 'index.html')


@require_GET
def upload_config_js(request: HttpRequest) -> HttpResponse:
    token = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    response = HttpResponse(
        '// Generated by Abies. Do not edit.\n'
        "'use strict';\n"
        f'const UPLOAD_TOKEN = {json.dumps(token)};\n',
        content_type='text/javascript; charset=utf-8',
    )
    apply_cache_control(response, CACHE_NO_STORE)
    return response


@require_GET
def asset(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path in {'reference.json', 'terreni.geojson', 'upload-config.js'}:
        raise Http404
    return _asset_response(request, asset_path)


def _asset_response(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path not in ASSET_FILES:
        raise Http404
    path = _static_path(asset_path)
    content_type = ASSET_CONTENT_TYPES.get(Path(asset_path).suffix)
    if content_type is None:
        raise Http404
    return conditional_file_response(
        request, path, content_type=content_type, cache_control=CACHE_NO_CACHE,
    )


def _static_path(asset_path: str) -> Path:
    found = finders.find(f'ipso/{asset_path}')
    if not found:
        raise Http404
    return Path(found)


@require_GET
def reference_json(request: HttpRequest) -> HttpResponse:
    """Current-client reference bundle, generated from Abies data.

    The existing Ipso UI still consumes the legacy display fields
    (`common`, `compresa`, `particella`) while the integrated upload path uses
    the added canonical Abies IDs (`id`, `region_id`, `parcel_id`).
    """
    payload = {
        'schema_version': SCHEMA_VERSION,
        'generated_at': django_timezone.now().astimezone(timezone.utc)
                       .isoformat(timespec='seconds').replace('+00:00', 'Z'),
        'species': _species_rows(),
        'parcels': _parcel_rows(),
        'ipsometrica': _ipsometrica(),
    }
    payload['reference_version'] = _reference_version(payload)
    return _json_response(payload, content_type='application/json')


def _species_rows() -> list[dict]:
    return [
        {
            'id': sp.id,
            'common': sp.common_name,
            'latin': sp.latin_name,
            'sort_order': sp.sort_order,
            'density': float(sp.density),
        }
        for sp in Species.objects.filter(active=True).order_by('sort_order', 'common_name')
    ]


def _parcel_rows() -> list[dict]:
    rows = [
        {
            'region_id': p.region_id,
            'region_name': p.region.name,
            'parcel_id': p.id,
            'compresa': p.region.name,
            'particella': p.name,
        }
        for p in (Parcel.objects
                  .select_related('region', 'eclass')
                  .filter(eclass__coppice=False))
    ]
    rows.sort(key=lambda p: (p['compresa'], _natural_key(p['particella'])))
    return rows


def _ipsometrica() -> dict:
    active = HypsoParamSet.objects.active().first()
    if active is None:
        return {}
    out: dict[str, dict[str, dict[str, float]]] = {}
    params = (HypsoParam.objects
              .filter(param_set=active, func=HYPSO_FUNC_LN)
              .select_related('region', 'species')
              .order_by('region__name', 'species__common_name'))
    for p in params:
        out.setdefault(p.region.name, {})[p.species.common_name] = {
            'a': float(p.a),
            'b': float(p.b),
            'hypso_param_set_id': active.id,
        }
    return out


def _reference_version(payload: dict) -> str:
    raw = json.dumps({
        'species': payload['species'],
        'parcels': payload['parcels'],
        'ipsometrica': payload['ipsometrica'],
    }, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()[:20]


@require_GET
def terreni_geojson(request: HttpRequest) -> HttpResponse:
    path = Path(settings.GEO_DIR) / 'terreni.geojson'
    if path.is_file():
        return conditional_file_response(
            request, path, content_type='application/geo+json',
            cache_control=CACHE_NO_CACHE,
        )
    return _json_response(
        {'type': 'FeatureCollection', 'features': []},
        content_type='application/geo+json', cache_control=CACHE_NO_CACHE,
    )


INBOX_COLUMNS = [
    'row_id', 'Ricevuto', 'Modalita', 'Operatore', 'Record', 'Stato',
    'Pacchetto', 'Destinazione', 'Errore',
]
STATE_LABELS = {
    IpsoUploadState.RECEIVED: 'Da importare',
    IpsoUploadState.IMPORTED: 'Importato',
    IpsoUploadState.REJECTED: 'Rifiutato',
    IpsoUploadState.CONFLICT: 'Conflitto',
}


@login_required
@require_GET
def inbox_data(request: HttpRequest) -> JsonResponse:
    uploads = IpsoUpload.objects.order_by('-received_at')
    payload = {
        'columns': INBOX_COLUMNS,
        'rows': [_inbox_row(u) for u in uploads],
        'pending_count': uploads.filter(state=IpsoUploadState.RECEIVED).count(),
    }
    return _api_json(payload)


@login_required
@require_GET
def upload_detail(request: HttpRequest, upload_id: int) -> JsonResponse:
    upload = _get_upload(upload_id)
    payload, file_error = _read_staged_payload(upload)
    session = payload.get('session', {}) if payload else {}
    records = payload.get('records', []) if payload else []
    return _api_json({
        'upload': _upload_metadata(upload),
        'session': session,
        'records': _preview_records(records),
        'record_count': len(records),
        'file_error': file_error,
        'targets': _martellate_targets(),
        'suggested_target_id': _suggested_harvest_item_id(upload.work_package_id),
    })


@login_required
@require_writer
@require_POST
def reject_upload(request: HttpRequest, upload_id: int) -> JsonResponse:
    upload = _get_upload(upload_id)
    if upload.state == IpsoUploadState.IMPORTED:
        return _api_json({
            'ok': False,
            'message': 'Un caricamento importato non puo essere rifiutato.',
        }, status=400)
    upload.state = IpsoUploadState.REJECTED
    upload.error_summary = _reject_reason(request)
    upload.save(update_fields=['state', 'error_summary'])
    return _api_json({'ok': True, 'upload': _upload_metadata(upload)})


@login_required
@require_writer
@require_POST
def import_martellate_upload(request: HttpRequest, upload_id: int) -> JsonResponse:
    upload = _get_upload(upload_id)
    if upload.mode != UPLOAD_MODE_MARTELLATE:
        return _api_json({'ok': False, 'message': 'Modalita non supportata.'}, status=400)
    if upload.state != IpsoUploadState.RECEIVED:
        return _api_json({
            'ok': False,
            'message': 'Solo i caricamenti da importare possono essere importati.',
        }, status=400)
    try:
        body = _request_json(request)
        item_id = _int(body, 'harvest_plan_item_id')
    except UploadValidationError as e:
        return _api_json({'ok': False, 'message': str(e)}, status=400)
    item = (HarvestPlanItem.objects
            .select_related('parcel__region', 'parcel__eclass', 'region', 'harvest_plan')
            .filter(id=item_id).first())
    if item is None:
        return _api_json({'ok': False, 'message': S.ERR_PLAN_ITEM_NOT_FOUND}, status=400)
    if item.state == HarvestPlanItemState.CLOSED:
        return _api_json({'ok': False, 'message': S.ERR_MARK_ITEM_CLOSED}, status=400)
    if not _is_valid_martellate_target(item):
        return _api_json({
            'ok': False,
            'message': 'Destinazione non valida per Martellate.',
        }, status=400)

    payload, file_error = _read_staged_payload(upload)
    if file_error:
        return _api_json({'ok': False, 'message': file_error}, status=400)
    rows, errors = _martellate_import_rows(upload, payload, item)
    if errors:
        return _api_json({'ok': False, 'message': '\n'.join(errors), 'errors': errors}, status=400)

    result = import_mark_rows(item, rows)
    upload.state = IpsoUploadState.IMPORTED
    upload.imported_at = django_timezone.now()
    upload.imported_by = request.user
    upload.target_type = TARGET_TYPE_HARVEST_PLAN_ITEM
    upload.target_id = item.id
    upload.error_summary = ''
    upload.save(update_fields=[
        'state', 'imported_at', 'imported_by', 'target_type', 'target_id',
        'error_summary',
    ])
    return _api_json({
        'ok': True,
        'imported': result.imported,
        'skipped_duplicates': result.skipped_duplicates,
        'upload': _upload_metadata(upload),
    })


@csrf_exempt
@require_POST
def upload_session(request: HttpRequest) -> JsonResponse:
    if not _upload_authorized(request):
        return _api_json({'ok': False, 'error': 'auth'}, status=401)
    try:
        payload = _request_json(request)
        normalized, csv_text = _validate_upload_payload(payload, request)
    except UploadValidationError as e:
        return _api_json({'ok': False, 'error': 'invalid_payload', 'detail': str(e)}, status=422)

    checksum = _payload_checksum(normalized)
    session_id = normalized['session']['session_id']
    existing = IpsoUpload.objects.filter(session_id=session_id).first()
    if existing is not None:
        if hmac.compare_digest(existing.checksum, checksum):
            return _api_json({
                'ok': True,
                'stored_as': existing.inbox_path,
                'duplicate': True,
            })
        existing.state = IpsoUploadState.CONFLICT
        existing.error_summary = 'Duplicate session_id with different content.'
        existing.save(update_fields=['state', 'error_summary'])
        return _api_json({'ok': False, 'error': 'conflict'}, status=409)

    inbox_path = _write_upload_files(session_id, normalized, checksum, csv_text)
    try:
        upload = IpsoUpload.objects.create(
            session_id=session_id,
            mode=normalized['session']['mode'],
            schema_version=normalized['session']['schema_version'],
            reference_version=normalized['session'].get('reference_version', ''),
            work_package_id=normalized['session'].get('work_package_id', ''),
            operator=normalized['session'].get('operator', ''),
            record_count=len(normalized['records']),
            checksum=checksum,
            inbox_path=str(inbox_path),
        )
    except IntegrityError:
        existing = IpsoUpload.objects.get(session_id=session_id)
        if hmac.compare_digest(existing.checksum, checksum):
            return _api_json({
                'ok': True,
                'stored_as': existing.inbox_path,
                'duplicate': True,
            })
        return _api_json({'ok': False, 'error': 'conflict'}, status=409)

    return _api_json({
        'ok': True,
        'stored_as': upload.inbox_path,
        'duplicate': False,
    })



def _get_upload(upload_id: int) -> IpsoUpload:
    try:
        return IpsoUpload.objects.get(id=upload_id)
    except IpsoUpload.DoesNotExist as e:
        raise Http404 from e


def _inbox_row(upload: IpsoUpload) -> list:
    return [
        upload.id,
        _format_dt(upload.received_at),
        upload.mode,
        upload.operator,
        upload.record_count,
        STATE_LABELS.get(upload.state, upload.state),
        upload.work_package_id,
        _target_label(upload),
        upload.error_summary,
    ]


def _upload_metadata(upload: IpsoUpload) -> dict:
    return {
        'id': upload.id,
        'session_id': upload.session_id,
        'mode': upload.mode,
        'schema_version': upload.schema_version,
        'reference_version': upload.reference_version,
        'work_package_id': upload.work_package_id,
        'operator': upload.operator,
        'record_count': upload.record_count,
        'checksum': upload.checksum,
        'state': upload.state,
        'state_label': STATE_LABELS.get(upload.state, upload.state),
        'received_at': _format_dt(upload.received_at),
        'imported_at': _format_dt(upload.imported_at),
        'target_type': upload.target_type,
        'target_id': upload.target_id,
        'target_label': _target_label(upload),
        'error_summary': upload.error_summary,
    }


def _target_label(upload: IpsoUpload) -> str:
    if upload.target_type == TARGET_TYPE_HARVEST_PLAN_ITEM and upload.target_id:
        item = (HarvestPlanItem.objects
                .select_related('harvest_plan', 'parcel__region', 'parcel__eclass', 'region')
                .filter(id=upload.target_id).first())
        if item is not None:
            return _harvest_item_label(item)
    if upload.target_type and upload.target_id:
        return f'{upload.target_type}:{upload.target_id}'
    return ''


def _format_dt(value) -> str:
    if not value:
        return ''
    return value.astimezone(timezone.utc).strftime('%Y-%m-%d %H:%M')


def _read_staged_payload(upload: IpsoUpload) -> tuple[dict, str]:
    path = Path(upload.inbox_path) / 'upload.json'
    try:
        return json.loads(path.read_text(encoding='utf-8')), ''
    except FileNotFoundError:
        return {}, 'File upload.json non trovato.'
    except json.JSONDecodeError:
        return {}, 'File upload.json non valido.'


def _preview_records(records: list) -> list[dict]:
    if not isinstance(records, list):
        return []
    species_ids = {
        r.get('species_id') for r in records
        if isinstance(r, dict) and type(r.get('species_id')) is int
    }
    parcel_ids = {
        r.get('parcel_id') for r in records
        if isinstance(r, dict) and type(r.get('parcel_id')) is int
    }
    species = {
        sp.id: sp.common_name
        for sp in Species.objects.filter(id__in=species_ids)
    }
    parcels = {
        p.id: f'{p.region.name} {p.name}'
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region')
    }
    out = []
    for i, row in enumerate(records[:500], start=1):
        if not isinstance(row, dict):
            continue
        out.append({
            'seq': row.get('client_record_id') or str(i),
            'date': row.get('date', ''),
            'parcel': parcels.get(row.get('parcel_id'), str(row.get('parcel_id', ''))),
            'species': species.get(row.get('species_id'), str(row.get('species_id', ''))),
            'number': row.get('number'),
            'd_cm': row.get('d_cm'),
            'h_m': row.get('h_m'),
            'h_measured': bool(row.get('h_measured')),
            'lat': row.get('lat'),
            'lon': row.get('lon'),
            'acc_m': row.get('acc_m'),
        })
    return out


def _reject_reason(request: HttpRequest) -> str:
    try:
        body = json.loads(request.body.decode('utf-8') or '{}')
    except (UnicodeDecodeError, json.JSONDecodeError):
        body = {}
    reason = body.get('reason', '') if isinstance(body, dict) else ''
    return reason.strip() or 'Rifiutato in revisione Abies.'


def _martellate_targets() -> list[dict]:
    items = (HarvestPlanItem.objects
             .select_related('harvest_plan', 'parcel__region', 'parcel__eclass', 'region')
             .exclude(state=HarvestPlanItemState.CLOSED)
             .order_by('harvest_plan__name', 'year_planned', 'id'))
    out = []
    for item in items:
        if _is_valid_martellate_target(item):
            out.append({'id': item.id, 'label': _harvest_item_label(item)})
    return out


def _is_valid_martellate_target(item: HarvestPlanItem) -> bool:
    if item.state == HarvestPlanItemState.CLOSED:
        return False
    return not (item.parcel_id and item.parcel.eclass.coppice)


def _harvest_item_label(item: HarvestPlanItem) -> str:
    if item.parcel_id:
        area = f'{item.parcel.region.name} {item.parcel.name}'
    elif item.region_id:
        area = item.region.name
    else:
        area = '-'
    state = HarvestPlanItemState(item.state).label
    return f'{item.harvest_plan.name} - {area} - {item.year_planned} ({state})'


def _suggested_harvest_item_id(work_package_id: str) -> int | None:
    raw = (work_package_id or '').strip()
    if raw.startswith('harvest:'):
        raw = raw.split(':', 1)[1]
    if not raw.isdigit():
        return None
    item_id = int(raw)
    item = (HarvestPlanItem.objects
            .select_related('parcel__eclass')
            .filter(id=item_id).first())
    if item is not None and _is_valid_martellate_target(item):
        return item_id
    return None


def _martellate_import_rows(
        upload: IpsoUpload, payload: dict, item: HarvestPlanItem,
) -> tuple[list[MarkImportRow], list[str]]:
    session = payload.get('session', {}) if isinstance(payload, dict) else {}
    records = payload.get('records', []) if isinstance(payload, dict) else []
    if not isinstance(records, list):
        return [], ['records deve essere un array.']

    species_ids = {
        r.get('species_id') for r in records
        if isinstance(r, dict) and type(r.get('species_id')) is int
    }
    parcel_ids = {
        r.get('parcel_id') for r in records
        if isinstance(r, dict) and type(r.get('parcel_id')) is int
    }
    species = {
        sp.id: sp
        for sp in Species.objects.filter(id__in=species_ids)
    }
    parcels = {
        p.id: p
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region', 'eclass')
    }
    item_region = item.region or (item.parcel.region if item.parcel else None)
    operator = (session.get('operator') or '').strip() if isinstance(session, dict) else ''

    rows = []
    errors = []
    for i, record in enumerate(records, start=1):
        if not isinstance(record, dict):
            errors.append(f'Record {i}: formato non valido.')
            continue
        parcel = parcels.get(record.get('parcel_id'))
        if parcel is None:
            errors.append(f'Record {i}: particella non trovata.')
            continue
        if item_region and parcel.region_id != item_region.id:
            errors.append(S.ERR_MARK_PARCEL_NOT_IN_REGION)
            continue
        sp = species.get(record.get('species_id'))
        if sp is None:
            errors.append(f'Record {i}: specie non trovata.')
            continue
        try:
            date = date_type.fromisoformat(str(record.get('date')))
            d_cm = int(record.get('d_cm'))
            h_m = Decimal(str(record.get('h_m')))
        except (TypeError, ValueError, InvalidOperation):
            errors.append(f'Record {i}: D/H/data non validi.')
            continue
        rows.append(MarkImportRow(
            date=date,
            parcel=parcel,
            species=sp,
            number=record.get('number'),
            d_cm=d_cm,
            h_m=h_m,
            h_measured=bool(record.get('h_measured')),
            lat=record.get('lat'),
            lon=record.get('lon'),
            acc_m=record.get('acc_m'),
            operator=operator,
            fingerprint=ipso_mark_fingerprint(upload.session_id, record),
        ))
    return rows, errors


def _upload_authorized(request: HttpRequest) -> bool:
    expected = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    if not expected:
        return True
    prefix = 'Bearer '
    header = request.headers.get('Authorization', '')
    if not header.startswith(prefix):
        return False
    return hmac.compare_digest(header[len(prefix):], expected)


def _request_json(request: HttpRequest) -> dict:
    try:
        payload = json.loads(request.body.decode('utf-8'))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise UploadValidationError('Malformed JSON.') from e
    if not isinstance(payload, dict):
        raise UploadValidationError('Payload must be an object.')
    return payload


def _validate_upload_payload(payload: dict, request: HttpRequest) -> tuple[dict, str | None]:
    session = _dict(payload, 'session')
    records = _list(payload, 'records')
    csv_text = payload.get('csv_text')
    if csv_text is not None and not isinstance(csv_text, str):
        raise UploadValidationError('csv_text must be a string when present.')

    normalized_session = _normalize_session(session)
    header_id = request.headers.get('X-Ipso-Session-Id', '')
    if header_id and header_id != normalized_session['session_id']:
        raise UploadValidationError('X-Ipso-Session-Id does not match session.session_id.')

    normalized_records = [_normalize_record(i, row) for i, row in enumerate(records, start=1)]
    _validate_record_ids(normalized_records)
    return {'session': normalized_session, 'records': normalized_records}, csv_text


def _normalize_session(session: dict) -> dict:
    session_id = _str(session, 'session_id')
    if not _SESSION_ID_RE.match(session_id):
        raise UploadValidationError('session_id must be a UUID.')
    mode = _str(session, 'mode')
    if mode != UPLOAD_MODE_MARTELLATE:
        raise UploadValidationError('Unsupported mode.')
    schema_version = _int(session, 'schema_version')
    if schema_version != UPLOAD_SCHEMA_VERSION:
        raise UploadValidationError('Unsupported schema_version.')
    normalized = {
        'session_id': session_id,
        'mode': mode,
        'schema_version': schema_version,
        'reference_version': _opt_str(session, 'reference_version'),
        'work_package_id': _opt_str(session, 'work_package_id'),
        'operator': _opt_str(session, 'operator'),
        'created_at': _opt_str(session, 'created_at'),
        'completed_at': _opt_str(session, 'completed_at'),
        'catastrofata': _bool(session, 'catastrofata'),
    }
    region_id = session.get('region_id')
    if region_id is not None:
        normalized['region_id'] = _int(session, 'region_id')
    return normalized


def _normalize_record(index: int, row: object) -> dict:
    if not isinstance(row, dict):
        raise UploadValidationError(f'Record {index}: must be an object.')
    date = _str(row, 'date')
    if not _DATE_RE.match(date):
        raise UploadValidationError(f'Record {index}: date must be YYYY-MM-DD.')
    d_cm = _int(row, 'd_cm')
    if d_cm <= 0:
        raise UploadValidationError(f'Record {index}: d_cm must be positive.')
    h_m = _decimal_str(row, 'h_m')
    if Decimal(h_m) <= 0:
        raise UploadValidationError(f'Record {index}: h_m must be positive.')
    return {
        'client_record_id': _str(row, 'client_record_id'),
        'date': date,
        'region_id': _int(row, 'region_id'),
        'parcel_id': _int(row, 'parcel_id'),
        'species_id': _int(row, 'species_id'),
        'number': _opt_int(row, 'number'),
        'd_cm': d_cm,
        'h_m': h_m,
        'h_measured': _bool(row, 'h_measured'),
        'hypso_param_set_id': _opt_int(row, 'hypso_param_set_id'),
        'lat': _opt_float(row, 'lat'),
        'lon': _opt_float(row, 'lon'),
        'acc_m': _opt_int(row, 'acc_m'),
    }


def _validate_record_ids(records: list[dict]) -> None:
    species_ids = {r['species_id'] for r in records}
    parcel_ids = {r['parcel_id'] for r in records}
    hypso_ids = {r['hypso_param_set_id'] for r in records if r['hypso_param_set_id'] is not None}
    valid_species = set(Species.objects.filter(id__in=species_ids).values_list('id', flat=True))
    parcels = {
        p.id: p.region_id
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region')
    }
    missing_species = species_ids - valid_species
    if missing_species:
        raise UploadValidationError(f'Unknown species_id: {min(missing_species)}.')
    missing_parcels = parcel_ids - set(parcels)
    if missing_parcels:
        raise UploadValidationError(f'Unknown parcel_id: {min(missing_parcels)}.')
    valid_hypso = set(HypsoParamSet.objects.filter(id__in=hypso_ids).values_list('id', flat=True))
    missing_hypso = hypso_ids - valid_hypso
    if missing_hypso:
        raise UploadValidationError(f'Unknown hypso_param_set_id: {min(missing_hypso)}.')
    for i, row in enumerate(records, start=1):
        if parcels[row['parcel_id']] != row['region_id']:
            raise UploadValidationError(f'Record {i}: parcel_id not in region_id.')


def _payload_checksum(payload: dict) -> str:
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


def _write_upload_files(
        session_id: str, payload: dict, checksum: str, csv_text: str | None,
) -> Path:
    now = django_timezone.now().astimezone(timezone.utc)
    session_dir = Path(settings.IPSO_INBOX_DIR) / f'{now.year:04d}' / f'{now.month:02d}' / session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(
        session_dir / 'upload.json',
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + '\n',
    )
    _atomic_write_text(session_dir / 'upload.sha256', checksum + '\n')
    if csv_text:
        _atomic_write_text(session_dir / 'export.csv', csv_text)
    return session_dir


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(path)


def _dict(payload: dict, key: str) -> dict:
    value = payload.get(key)
    if not isinstance(value, dict):
        raise UploadValidationError(f'{key} must be an object.')
    return value


def _list(payload: dict, key: str) -> list:
    value = payload.get(key)
    if not isinstance(value, list):
        raise UploadValidationError(f'{key} must be an array.')
    return value


def _str(payload: dict, key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise UploadValidationError(f'{key} is required.')
    return value.strip()


def _opt_str(payload: dict, key: str) -> str:
    value = payload.get(key, '')
    if value is None:
        return ''
    if not isinstance(value, str):
        raise UploadValidationError(f'{key} must be a string.')
    return value.strip()


def _int(payload: dict, key: str) -> int:
    value = payload.get(key)
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer.')
    return value


def _opt_int(payload: dict, key: str) -> int | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer or null.')
    return value


def _bool(payload: dict, key: str) -> bool:
    value = payload.get(key)
    if type(value) is not bool:
        raise UploadValidationError(f'{key} must be a boolean.')
    return value


def _opt_float(payload: dict, key: str) -> float | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) not in {int, float}:
        raise UploadValidationError(f'{key} must be a number or null.')
    out = float(value)
    if not math.isfinite(out):
        raise UploadValidationError(f'{key} must be finite.')
    return out


def _decimal_str(payload: dict, key: str) -> str:
    value = payload.get(key)
    if type(value) not in {int, float, str}:
        raise UploadValidationError(f'{key} must be a decimal value.')
    try:
        dec = Decimal(str(value))
    except InvalidOperation as e:
        raise UploadValidationError(f'{key} must be a decimal value.') from e
    if not dec.is_finite():
        raise UploadValidationError(f'{key} must be finite.')
    return format(dec, 'f')


def _json_response(
        payload: dict, *, content_type: str,
        cache_control: str = CACHE_NO_STORE,
) -> HttpResponse:
    response = HttpResponse(
        json.dumps(payload, ensure_ascii=False, separators=(',', ':')),
        content_type=content_type,
    )
    apply_cache_control(response, cache_control)
    return response


def _api_json(payload: dict, *, status: int = 200) -> JsonResponse:
    response = JsonResponse(payload, status=status)
    apply_cache_control(response, CACHE_NO_STORE)
    return response
