"""Serve the Ipso offline PWA from the Abies origin."""

from __future__ import annotations

import hashlib
import hmac
import json
import math
import re
from datetime import timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.conf import settings
from django.contrib.staticfiles import finders
from django.db import IntegrityError
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.utils import timezone as django_timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST

from apps.base.http import (
    CACHE_NO_CACHE, CACHE_NO_STORE, apply_cache_control,
    conditional_file_response,
)
from apps.base.models import HYPSO_FUNC_LN, HypsoParam, HypsoParamSet, Parcel, Species
from apps.ipso.models import IpsoUpload, IpsoUploadState

SCHEMA_VERSION = 1
UPLOAD_SCHEMA_VERSION = 1
UPLOAD_MODE_MARTELLATE = 'martellate'

ASSET_CONTENT_TYPES = {
    '.css': 'text/css; charset=utf-8',
    '.gif': 'image/gif',
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.png': 'image/png',
    '.webmanifest': 'application/manifest+json',
}

ASSET_FILES = {
    'app.js',
    'csv.js',
    'download.js',
    'geo.js',
    'gps.js',
    'index.html',
    'ipso.js',
    'manifest.webmanifest',
    'numpad.js',
    'parcel-locator.js',
    'session.js',
    'store.js',
    'strings.js',
    'style.css',
    'sw.js',
    'upload.js',
    'version.js',
    'img/f.gif',
    'img/l.gif',
    'img/icon-192.png',
    'img/icon-512.png',
    'img/icon-512-maskable.png',
}

_NATKEY_RE = re.compile(r'(\d+)')
_DATE_RE = re.compile(r'^\d{4}-\d{2}-\d{2}$')
_SESSION_ID_RE = re.compile(
    r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
    r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
)


class UploadValidationError(ValueError):
    pass


def _natural_key(value: str) -> list:
    return [int(p) if p.isdigit() else p.lower() for p in _NATKEY_RE.split(value)]


@require_GET
def index(request: HttpRequest) -> HttpResponse:
    return _asset_response(request, 'index.html')


@require_GET
def upload_config_js(request: HttpRequest) -> HttpResponse:
    token = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    response = HttpResponse(
        '// Generated by Abies. Do not edit.\n'
        "'use strict';\n"
        f'const UPLOAD_TOKEN = {json.dumps(token)};\n',
        content_type='text/javascript; charset=utf-8',
    )
    apply_cache_control(response, CACHE_NO_STORE)
    return response


@require_GET
def asset(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path in {'reference.json', 'terreni.geojson', 'upload-config.js'}:
        raise Http404
    return _asset_response(request, asset_path)


def _asset_response(request: HttpRequest, asset_path: str) -> HttpResponse:
    if asset_path not in ASSET_FILES:
        raise Http404
    path = _static_path(asset_path)
    content_type = ASSET_CONTENT_TYPES.get(Path(asset_path).suffix)
    if content_type is None:
        raise Http404
    return conditional_file_response(
        request, path, content_type=content_type, cache_control=CACHE_NO_CACHE,
    )


def _static_path(asset_path: str) -> Path:
    found = finders.find(f'ipso/{asset_path}')
    if not found:
        raise Http404
    return Path(found)


@require_GET
def reference_json(request: HttpRequest) -> HttpResponse:
    """Current-client reference bundle, generated from Abies data.

    The existing Ipso UI still consumes the legacy display fields
    (`common`, `compresa`, `particella`) while the integrated upload path uses
    the added canonical Abies IDs (`id`, `region_id`, `parcel_id`).
    """
    payload = {
        'schema_version': SCHEMA_VERSION,
        'generated_at': django_timezone.now().astimezone(timezone.utc)
                       .isoformat(timespec='seconds').replace('+00:00', 'Z'),
        'species': _species_rows(),
        'parcels': _parcel_rows(),
        'ipsometrica': _ipsometrica(),
    }
    return _json_response(payload, content_type='application/json')


def _species_rows() -> list[dict]:
    return [
        {
            'id': sp.id,
            'common': sp.common_name,
            'latin': sp.latin_name,
            'sort_order': sp.sort_order,
            'density': float(sp.density),
        }
        for sp in Species.objects.filter(active=True).order_by('sort_order', 'common_name')
    ]


def _parcel_rows() -> list[dict]:
    rows = [
        {
            'region_id': p.region_id,
            'region_name': p.region.name,
            'parcel_id': p.id,
            'compresa': p.region.name,
            'particella': p.name,
        }
        for p in (Parcel.objects
                  .select_related('region', 'eclass')
                  .filter(eclass__coppice=False))
    ]
    rows.sort(key=lambda p: (p['compresa'], _natural_key(p['particella'])))
    return rows


def _ipsometrica() -> dict:
    active = HypsoParamSet.objects.active().first()
    if active is None:
        return {}
    out: dict[str, dict[str, dict[str, float]]] = {}
    params = (HypsoParam.objects
              .filter(param_set=active, func=HYPSO_FUNC_LN)
              .select_related('region', 'species')
              .order_by('region__name', 'species__common_name'))
    for p in params:
        out.setdefault(p.region.name, {})[p.species.common_name] = {
            'a': float(p.a),
            'b': float(p.b),
        }
    return out


@require_GET
def terreni_geojson(request: HttpRequest) -> HttpResponse:
    path = Path(settings.GEO_DIR) / 'terreni.geojson'
    if path.is_file():
        return conditional_file_response(
            request, path, content_type='application/geo+json',
            cache_control=CACHE_NO_CACHE,
        )
    return _json_response(
        {'type': 'FeatureCollection', 'features': []},
        content_type='application/geo+json', cache_control=CACHE_NO_CACHE,
    )


@csrf_exempt
@require_POST
def upload_session(request: HttpRequest) -> JsonResponse:
    if not _upload_authorized(request):
        return _api_json({'ok': False, 'error': 'auth'}, status=401)
    try:
        payload = _request_json(request)
        normalized, csv_text = _validate_upload_payload(payload, request)
    except UploadValidationError as e:
        return _api_json({'ok': False, 'error': 'invalid_payload', 'detail': str(e)}, status=422)

    checksum = _payload_checksum(normalized)
    session_id = normalized['session']['session_id']
    existing = IpsoUpload.objects.filter(session_id=session_id).first()
    if existing is not None:
        if hmac.compare_digest(existing.checksum, checksum):
            return _api_json({
                'ok': True,
                'stored_as': existing.inbox_path,
                'duplicate': True,
            })
        existing.state = IpsoUploadState.CONFLICT
        existing.error_summary = 'Duplicate session_id with different content.'
        existing.save(update_fields=['state', 'error_summary'])
        return _api_json({'ok': False, 'error': 'conflict'}, status=409)

    inbox_path = _write_upload_files(session_id, normalized, checksum, csv_text)
    try:
        upload = IpsoUpload.objects.create(
            session_id=session_id,
            mode=normalized['session']['mode'],
            schema_version=normalized['session']['schema_version'],
            reference_version=normalized['session'].get('reference_version', ''),
            work_package_id=normalized['session'].get('work_package_id', ''),
            operator=normalized['session'].get('operator', ''),
            record_count=len(normalized['records']),
            checksum=checksum,
            inbox_path=str(inbox_path),
        )
    except IntegrityError:
        existing = IpsoUpload.objects.get(session_id=session_id)
        if hmac.compare_digest(existing.checksum, checksum):
            return _api_json({
                'ok': True,
                'stored_as': existing.inbox_path,
                'duplicate': True,
            })
        return _api_json({'ok': False, 'error': 'conflict'}, status=409)

    return _api_json({
        'ok': True,
        'stored_as': upload.inbox_path,
        'duplicate': False,
    })


def _upload_authorized(request: HttpRequest) -> bool:
    expected = getattr(settings, 'IPSO_UPLOAD_TOKEN', '')
    if not expected:
        return True
    prefix = 'Bearer '
    header = request.headers.get('Authorization', '')
    if not header.startswith(prefix):
        return False
    return hmac.compare_digest(header[len(prefix):], expected)


def _request_json(request: HttpRequest) -> dict:
    try:
        payload = json.loads(request.body.decode('utf-8'))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise UploadValidationError('Malformed JSON.') from e
    if not isinstance(payload, dict):
        raise UploadValidationError('Payload must be an object.')
    return payload


def _validate_upload_payload(payload: dict, request: HttpRequest) -> tuple[dict, str | None]:
    session = _dict(payload, 'session')
    records = _list(payload, 'records')
    csv_text = payload.get('csv_text')
    if csv_text is not None and not isinstance(csv_text, str):
        raise UploadValidationError('csv_text must be a string when present.')

    normalized_session = _normalize_session(session)
    header_id = request.headers.get('X-Ipso-Session-Id', '')
    if header_id and header_id != normalized_session['session_id']:
        raise UploadValidationError('X-Ipso-Session-Id does not match session.session_id.')

    normalized_records = [_normalize_record(i, row) for i, row in enumerate(records, start=1)]
    _validate_record_ids(normalized_records)
    return {'session': normalized_session, 'records': normalized_records}, csv_text


def _normalize_session(session: dict) -> dict:
    session_id = _str(session, 'session_id')
    if not _SESSION_ID_RE.match(session_id):
        raise UploadValidationError('session_id must be a UUID.')
    mode = _str(session, 'mode')
    if mode != UPLOAD_MODE_MARTELLATE:
        raise UploadValidationError('Unsupported mode.')
    schema_version = _int(session, 'schema_version')
    if schema_version != UPLOAD_SCHEMA_VERSION:
        raise UploadValidationError('Unsupported schema_version.')
    normalized = {
        'session_id': session_id,
        'mode': mode,
        'schema_version': schema_version,
        'reference_version': _opt_str(session, 'reference_version'),
        'work_package_id': _opt_str(session, 'work_package_id'),
        'operator': _opt_str(session, 'operator'),
        'created_at': _opt_str(session, 'created_at'),
        'completed_at': _opt_str(session, 'completed_at'),
        'catastrofata': _bool(session, 'catastrofata'),
    }
    region_id = session.get('region_id')
    if region_id is not None:
        normalized['region_id'] = _int(session, 'region_id')
    return normalized


def _normalize_record(index: int, row: object) -> dict:
    if not isinstance(row, dict):
        raise UploadValidationError(f'Record {index}: must be an object.')
    date = _str(row, 'date')
    if not _DATE_RE.match(date):
        raise UploadValidationError(f'Record {index}: date must be YYYY-MM-DD.')
    d_cm = _int(row, 'd_cm')
    if d_cm <= 0:
        raise UploadValidationError(f'Record {index}: d_cm must be positive.')
    h_m = _decimal_str(row, 'h_m')
    if Decimal(h_m) <= 0:
        raise UploadValidationError(f'Record {index}: h_m must be positive.')
    return {
        'client_record_id': _str(row, 'client_record_id'),
        'date': date,
        'region_id': _int(row, 'region_id'),
        'parcel_id': _int(row, 'parcel_id'),
        'species_id': _int(row, 'species_id'),
        'number': _opt_int(row, 'number'),
        'd_cm': d_cm,
        'h_m': h_m,
        'h_measured': _bool(row, 'h_measured'),
        'lat': _opt_float(row, 'lat'),
        'lon': _opt_float(row, 'lon'),
        'acc_m': _opt_int(row, 'acc_m'),
    }


def _validate_record_ids(records: list[dict]) -> None:
    species_ids = {r['species_id'] for r in records}
    parcel_ids = {r['parcel_id'] for r in records}
    valid_species = set(Species.objects.filter(id__in=species_ids).values_list('id', flat=True))
    parcels = {
        p.id: p.region_id
        for p in Parcel.objects.filter(id__in=parcel_ids).select_related('region')
    }
    missing_species = species_ids - valid_species
    if missing_species:
        raise UploadValidationError(f'Unknown species_id: {min(missing_species)}.')
    missing_parcels = parcel_ids - set(parcels)
    if missing_parcels:
        raise UploadValidationError(f'Unknown parcel_id: {min(missing_parcels)}.')
    for i, row in enumerate(records, start=1):
        if parcels[row['parcel_id']] != row['region_id']:
            raise UploadValidationError(f'Record {i}: parcel_id not in region_id.')


def _payload_checksum(payload: dict) -> str:
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


def _write_upload_files(
        session_id: str, payload: dict, checksum: str, csv_text: str | None,
) -> Path:
    now = django_timezone.now().astimezone(timezone.utc)
    session_dir = Path(settings.IPSO_INBOX_DIR) / f'{now.year:04d}' / f'{now.month:02d}' / session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(
        session_dir / 'upload.json',
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + '\n',
    )
    _atomic_write_text(session_dir / 'upload.sha256', checksum + '\n')
    if csv_text:
        _atomic_write_text(session_dir / 'export.csv', csv_text)
    return session_dir


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(path)


def _dict(payload: dict, key: str) -> dict:
    value = payload.get(key)
    if not isinstance(value, dict):
        raise UploadValidationError(f'{key} must be an object.')
    return value


def _list(payload: dict, key: str) -> list:
    value = payload.get(key)
    if not isinstance(value, list):
        raise UploadValidationError(f'{key} must be an array.')
    return value


def _str(payload: dict, key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise UploadValidationError(f'{key} is required.')
    return value.strip()


def _opt_str(payload: dict, key: str) -> str:
    value = payload.get(key, '')
    if value is None:
        return ''
    if not isinstance(value, str):
        raise UploadValidationError(f'{key} must be a string.')
    return value.strip()


def _int(payload: dict, key: str) -> int:
    value = payload.get(key)
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer.')
    return value


def _opt_int(payload: dict, key: str) -> int | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) is not int:
        raise UploadValidationError(f'{key} must be an integer or null.')
    return value


def _bool(payload: dict, key: str) -> bool:
    value = payload.get(key)
    if type(value) is not bool:
        raise UploadValidationError(f'{key} must be a boolean.')
    return value


def _opt_float(payload: dict, key: str) -> float | None:
    value = payload.get(key)
    if value is None:
        return None
    if type(value) not in {int, float}:
        raise UploadValidationError(f'{key} must be a number or null.')
    out = float(value)
    if not math.isfinite(out):
        raise UploadValidationError(f'{key} must be finite.')
    return out


def _decimal_str(payload: dict, key: str) -> str:
    value = payload.get(key)
    if type(value) not in {int, float, str}:
        raise UploadValidationError(f'{key} must be a decimal value.')
    try:
        dec = Decimal(str(value))
    except InvalidOperation as e:
        raise UploadValidationError(f'{key} must be a decimal value.') from e
    if not dec.is_finite():
        raise UploadValidationError(f'{key} must be finite.')
    return format(dec, 'f')


def _json_response(
        payload: dict, *, content_type: str,
        cache_control: str = CACHE_NO_STORE,
) -> HttpResponse:
    response = HttpResponse(
        json.dumps(payload, ensure_ascii=False, separators=(',', ':')),
        content_type=content_type,
    )
    apply_cache_control(response, cache_control)
    return response


def _api_json(payload: dict, *, status: int = 200) -> JsonResponse:
    response = JsonResponse(payload, status=status)
    apply_cache_control(response, CACHE_NO_STORE)
    return response
