# Generated by Django 6.0.4 on 2026-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("default_landing_page", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "impostazioni sito",
                "verbose_name_plural": "impostazioni sito",
            },
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="landing_page",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="landing_page",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
