# Generated by Django 6.0.4 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_sitesettings_historicaluser_landing_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treemark",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
