# Generated by Django 6.0.4 on 2026-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_historicalcrew_historicalspecies_historicaltractor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "specie",
                "verbose_name_plural": "specie",
            },
        ),
        migrations.AddField(
            model_name="historicalspecies",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="species",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
