# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_treemark_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.UniqueConstraint(
                fields=("harvest_plan_item", "number"),
                name="uniq_tree_mark_item_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.UniqueConstraint(
                fields=("sample", "number", "shoot"),
                name="uniq_tree_sample_number_shoot",
            ),
        ),
    ]
