# Generated by Django 6.0.4 on 2026-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_treemark_import_fingerprint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalSample",
        ),
    ]
