# Generated by Django 6.0.4 on 2026-07-16 10:26

import django.db.models.deletion
from django.db import migrations, models


SAMPLE_GRID_MATCH_DROP = """
DROP TRIGGER IF EXISTS sample_grid_match_insert;
DROP TRIGGER IF EXISTS sample_grid_match_update;
"""

SAMPLE_GRID_MATCH_INSERT = """
CREATE TRIGGER IF NOT EXISTS sample_grid_match_insert
BEFORE INSERT ON base_sample
FOR EACH ROW
WHEN (
    SELECT CASE
        WHEN survey.sample_grid_id IS NULL AND NEW.sample_area_id IS NOT NULL THEN 1
        WHEN survey.sample_grid_id IS NOT NULL AND NEW.sample_area_id IS NULL THEN 1
        WHEN survey.sample_grid_id IS NOT NULL
             AND sample_area.sample_grid_id != survey.sample_grid_id THEN 1
        ELSE 0
    END
    FROM base_survey AS survey
    LEFT JOIN base_samplearea AS sample_area ON sample_area.id = NEW.sample_area_id
    WHERE survey.id = NEW.survey_id
)
BEGIN
    SELECT RAISE(ABORT, 'sample_grid/sample_area mismatch');
END;
"""

SAMPLE_GRID_MATCH_UPDATE = """
CREATE TRIGGER IF NOT EXISTS sample_grid_match_update
BEFORE UPDATE OF survey_id, sample_area_id ON base_sample
FOR EACH ROW
WHEN (
    SELECT CASE
        WHEN survey.sample_grid_id IS NULL AND NEW.sample_area_id IS NOT NULL THEN 1
        WHEN survey.sample_grid_id IS NOT NULL AND NEW.sample_area_id IS NULL THEN 1
        WHEN survey.sample_grid_id IS NOT NULL
             AND sample_area.sample_grid_id != survey.sample_grid_id THEN 1
        ELSE 0
    END
    FROM base_survey AS survey
    LEFT JOIN base_samplearea AS sample_area ON sample_area.id = NEW.sample_area_id
    WHERE survey.id = NEW.survey_id
)
BEGIN
    SELECT RAISE(ABORT, 'sample_grid/sample_area mismatch');
END;
"""

OLD_SAMPLE_GRID_MATCH_INSERT = """
CREATE TRIGGER IF NOT EXISTS sample_grid_match_insert
BEFORE INSERT ON base_sample
FOR EACH ROW
WHEN (
    SELECT survey.sample_grid_id != sample_area.sample_grid_id
    FROM base_survey AS survey, base_samplearea AS sample_area
    WHERE survey.id = NEW.survey_id AND sample_area.id = NEW.sample_area_id
)
BEGIN
    SELECT RAISE(ABORT, 'sample_grid mismatch: survey.sample_grid != sample_area.sample_grid');
END;
"""

OLD_SAMPLE_GRID_MATCH_UPDATE = """
CREATE TRIGGER IF NOT EXISTS sample_grid_match_update
BEFORE UPDATE OF survey_id, sample_area_id ON base_sample
FOR EACH ROW
WHEN (
    SELECT survey.sample_grid_id != sample_area.sample_grid_id
    FROM base_survey AS survey, base_samplearea AS sample_area
    WHERE survey.id = NEW.survey_id AND sample_area.id = NEW.sample_area_id
)
BEGIN
    SELECT RAISE(ABORT, 'sample_grid mismatch: survey.sample_grid != sample_area.sample_grid');
END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_delete_historicalsample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.samplearea",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="sample_grid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.samplegrid",
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(active=False)
                    | models.Q(sample_grid__isnull=False)
                ),
                name="survey_active_requires_sample_grid",
            ),
        ),
        migrations.RunSQL(
            (
                SAMPLE_GRID_MATCH_DROP
                + SAMPLE_GRID_MATCH_INSERT
                + SAMPLE_GRID_MATCH_UPDATE
            ),
            reverse_sql=(
                SAMPLE_GRID_MATCH_DROP
                + OLD_SAMPLE_GRID_MATCH_INSERT
                + OLD_SAMPLE_GRID_MATCH_UPDATE
            ),
        ),
    ]
