# Generated by Django 6.0.4 on 2026-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_allow_unstructured_surveys"),
    ]

    operations = [
        migrations.AddField(
            model_name="treesample",
            name="h_measured",
            field=models.BooleanField(default=False),
        ),
    ]
