# Generated by Codex on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


BACKFILL_TREE_SAMPLE_OBSERVATION_FIELDS = """
UPDATE base_treesample
SET
    parcel_id = COALESCE(
        (
            SELECT base_samplearea.parcel_id
            FROM base_sample
            JOIN base_samplearea
              ON base_samplearea.id = base_sample.sample_area_id
            WHERE base_sample.id = base_treesample.sample_id
        ),
        (
            SELECT base_tree.parcel_id
            FROM base_tree
            WHERE base_tree.id = base_treesample.tree_id
        )
    ),
    lat = (
        SELECT base_tree.lat
        FROM base_tree
        WHERE base_tree.id = base_treesample.tree_id
    ),
    lon = (
        SELECT base_tree.lon
        FROM base_tree
        WHERE base_tree.id = base_treesample.tree_id
    ),
    acc_m = (
        SELECT base_tree.acc_m
        FROM base_tree
        WHERE base_tree.id = base_treesample.tree_id
    )
WHERE parcel_id IS NULL;
"""

BACKFILL_TREE_MARK_PARCELS = """
UPDATE base_treemark
SET parcel_id = (
    SELECT base_tree.parcel_id
    FROM base_tree
    WHERE base_tree.id = base_treemark.tree_id
)
WHERE parcel_id IS NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_add_tree_sample_h_measured"),
    ]

    operations = [
        migrations.AddField(
            model_name="treemark",
            name="parcel",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.parcel",
            ),
        ),
        migrations.AddField(
            model_name="treesample",
            name="parcel",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.parcel",
            ),
        ),
        migrations.AddField(
            model_name="treesample",
            name="preserved_number",
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="treesample",
            name="lat",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="treesample",
            name="lon",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="treesample",
            name="acc_m",
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="treesample",
            name="operator",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="treesample",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="treesample",
            name="import_fingerprint",
            field=models.CharField(null=True, blank=True, max_length=67),
        ),
        migrations.RunSQL(
            BACKFILL_TREE_SAMPLE_OBSERVATION_FIELDS + BACKFILL_TREE_MARK_PARCELS,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="treemark",
            name="parcel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.parcel",
            ),
        ),
        migrations.AlterField(
            model_name="treesample",
            name="parcel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.parcel",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.UniqueConstraint(
                fields=("sample", "parcel", "preserved_number"),
                condition=models.Q(preserved_number__isnull=False),
                name="uniq_tree_sample_preserved_number_per_sample_parcel",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(preserved_number__isnull=True)
                    | models.Q(preserved_number__gt=0)
                ),
                name="tree_sample_preserved_number_positive",
            ),
        ),
    ]
