# Generated by Codex on 2026-07-19

from datetime import date as date_type

from django.db import migrations, models


PRESERVED_HISTORY_SURVEY_NAME = 'Alberi da preservare - storico'
PRESERVED_HISTORY_SURVEY_DESCRIPTION = (
    'Rilevamento libero generato dalla migrazione degli alberi PAI storici.'
)
PRESERVED_LEGACY_UNKNOWN_DATE = date_type(1970, 1, 1)
PRESERVED_TREES_DIGEST = 'preserved_trees'


def migrate_preserved_trees(apps, schema_editor):
    Survey = apps.get_model('base', 'Survey')
    Sample = apps.get_model('base', 'Sample')
    TreePreserved = apps.get_model('base', 'TreePreserved')
    TreeSample = apps.get_model('base', 'TreeSample')

    if not TreePreserved.objects.exists():
        return

    bad_measurements = list(
        TreePreserved.objects
        .filter(d_cm__isnull=True)
        .values_list('id', flat=True)
    )
    if bad_measurements:
        raise RuntimeError(
            'Cannot migrate TreePreserved rows without diameter to TreeSample: '
            + ', '.join(str(pk) for pk in sorted(set(bad_measurements)))
        )

    survey, created = Survey.objects.get_or_create(
        name=PRESERVED_HISTORY_SURVEY_NAME,
        defaults={
            'sample_grid': None,
            'description': PRESERVED_HISTORY_SURVEY_DESCRIPTION,
            'active': False,
        },
    )
    if survey.sample_grid_id is not None:
        raise RuntimeError(
            f'Survey {PRESERVED_HISTORY_SURVEY_NAME!r} already exists and is structured'
        )
    if not created and survey.active:
        survey.active = False
        survey.save(update_fields=['active'])

    sample_by_key = {}
    rows = (
        TreePreserved.objects
        .select_related('tree')
        .order_by('date', 'parcel_id', 'number', 'id')
    )
    for pai in rows:
        sample_date = pai.date or PRESERVED_LEGACY_UNKNOWN_DATE
        key = (sample_date, pai.parcel_id)
        sample = sample_by_key.get(key)
        if sample is None:
            sample = Sample.objects.create(
                sample_area=None, survey=survey, date=sample_date,
            )
            sample_by_key[key] = sample
        if TreeSample.objects.filter(
                sample=sample, parcel_id=pai.parcel_id,
                preserved_number=pai.number,
        ).exists():
            continue
        TreeSample.objects.create(
            sample=sample,
            tree_id=pai.tree_id,
            parcel_id=pai.parcel_id,
            number=pai.number,
            preserved_number=pai.number,
            shoot=0,
            standard=False,
            d_cm=pai.d_cm,
            h_m=pai.h_m,
            h_measured=bool(pai.h_measured and pai.h_m is not None),
            l10_mm=0,
            volume_m3=pai.volume_m3,
            mass_q=pai.mass_q,
            lat=pai.lat,
            lon=pai.lon,
            acc_m=pai.acc_m,
            operator=pai.operator,
            note=pai.note,
        )
        tree = pai.tree
        changed = []
        if not tree.preserved:
            tree.preserved = True
            changed.append('preserved')
        if tree.parcel_id != pai.parcel_id:
            tree.parcel_id = pai.parcel_id
            changed.append('parcel')
        if tree.lat != pai.lat:
            tree.lat = pai.lat
            changed.append('lat')
        if tree.lon != pai.lon:
            tree.lon = pai.lon
            changed.append('lon')
        if tree.acc_m != pai.acc_m:
            tree.acc_m = pai.acc_m
            changed.append('acc_m')
        if changed:
            tree.save(update_fields=changed)

    mark_digest_stale(apps, PRESERVED_TREES_DIGEST)


def mark_digest_stale(apps, name):
    DigestStatus = apps.get_model('base', 'DigestStatus')
    status, created = DigestStatus.objects.get_or_create(
        name=name, defaults={'stale': True, 'dirty_seq': 1},
    )
    if not created:
        status.stale = True
        status.dirty_seq += 1
        status.save(update_fields=['stale', 'dirty_seq'])


def reverse_migration(apps, schema_editor):
    # The legacy TreePreserved table is retained, so reversing this migration
    # does not need to reconstruct legacy rows.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_tree_observation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treesample',
            name='h_m',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='treesample',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(preserved_number__isnull=False)
                    | models.Q(h_m__isnull=False)
                ),
                name='tree_sample_h_m_required_unless_preserved',
            ),
        ),
        migrations.AddConstraint(
            model_name='treesample',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(h_m__isnull=False) | models.Q(h_measured=False)
                ),
                name='tree_sample_h_measured_false_without_h_m',
            ),
        ),
        migrations.RunPython(migrate_preserved_trees, reverse_migration),
    ]
