# Generated by Django 6.0.4 on 2026-07-21 05:56

from django.db import migrations, models


HARVEST_TRIGGER_DROP = """
DROP TRIGGER IF EXISTS harvest_region_xor_parcel_insert;
DROP TRIGGER IF EXISTS harvest_region_xor_parcel_update;
DROP TRIGGER IF EXISTS harvest_parcel_consistency_insert;
DROP TRIGGER IF EXISTS harvest_parcel_consistency_update;
DROP TRIGGER IF EXISTS harvest_flags_consistency_insert;
DROP TRIGGER IF EXISTS harvest_flags_consistency_update;
"""

HARVEST_TRIGGER_CREATE = """
CREATE TRIGGER IF NOT EXISTS harvest_region_xor_parcel_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN (NEW.region_id IS NULL) = (NEW.parcel_id IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'harvest: exactly one of region or parcel must be set');
END;

CREATE TRIGGER IF NOT EXISTS harvest_region_xor_parcel_update
BEFORE UPDATE OF region_id, parcel_id ON prelievi_harvest
FOR EACH ROW
WHEN (NEW.region_id IS NULL) = (NEW.parcel_id IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'harvest: exactly one of region or parcel must be set');
END;

CREATE TRIGGER IF NOT EXISTS harvest_parcel_consistency_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND (
        (NEW.parcel_id IS NOT NULL AND (
            hpi.parcel_id = NEW.parcel_id
            OR hpi.region_id = (SELECT region_id FROM base_parcel WHERE id = NEW.parcel_id)))
        OR (NEW.parcel_id IS NULL AND hpi.region_id = NEW.region_id)
      )
)
BEGIN
    SELECT RAISE(ABORT, 'harvest.parcel/region does not match linked harvest_plan_item');
END;

CREATE TRIGGER IF NOT EXISTS harvest_parcel_consistency_update
BEFORE UPDATE OF parcel_id, region_id, harvest_plan_item_id ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND (
        (NEW.parcel_id IS NOT NULL AND (
            hpi.parcel_id = NEW.parcel_id
            OR hpi.region_id = (SELECT region_id FROM base_parcel WHERE id = NEW.parcel_id)))
        OR (NEW.parcel_id IS NULL AND hpi.region_id = NEW.region_id)
      )
)
BEGIN
    SELECT RAISE(ABORT, 'harvest.parcel/region does not match linked harvest_plan_item');
END;

CREATE TRIGGER IF NOT EXISTS harvest_flags_consistency_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND hpi.damaged   = NEW.damaged
      AND hpi.unhealthy = NEW.unhealthy
      AND hpi.psr       = NEW.psr
)
BEGIN
    SELECT RAISE(ABORT, 'harvest flags must match linked harvest_plan_item flags');
END;

CREATE TRIGGER IF NOT EXISTS harvest_flags_consistency_update
BEFORE UPDATE OF damaged, unhealthy, psr, harvest_plan_item_id ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND hpi.damaged   = NEW.damaged
      AND hpi.unhealthy = NEW.unhealthy
      AND hpi.psr       = NEW.psr
)
BEGIN
    SELECT RAISE(ABORT, 'harvest flags must match linked harvest_plan_item flags');
END;
"""

PARCEL_COPPICE_METADATA_DROP = """
DROP TRIGGER IF EXISTS parcel_coppice_metadata_insert;
DROP TRIGGER IF EXISTS parcel_coppice_metadata_update;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_insert;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_update;
DROP TRIGGER IF EXISTS eclass_coppice_metadata_update;
DROP TRIGGER IF EXISTS eclass_highforest_metadata_update;
"""

PARCEL_COPPICE_METADATA_TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS eclass_coppice_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 1
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NULL OR p.standards_per_ha IS NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS eclass_highforest_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 0
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NOT NULL OR p.standards_per_ha IS NOT NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_migrate_preserved_trees_to_samples"),
        ("prelievi", "0003_harvest_consistency_triggers"),
    ]

    operations = [
        migrations.RunSQL(
            HARVEST_TRIGGER_DROP,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="cutting_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="intervention_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="standards_per_ha",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="cutting_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="intervention_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="standards_per_ha",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            HARVEST_TRIGGER_CREATE,
            reverse_sql=HARVEST_TRIGGER_DROP,
        ),
        migrations.RunSQL(
            PARCEL_COPPICE_METADATA_DROP + PARCEL_COPPICE_METADATA_TRIGGERS,
            reverse_sql=PARCEL_COPPICE_METADATA_DROP,
        ),
    ]
