# Generated by Django 6.0.4 on 2026-07-21 05:56

from django.db import migrations, models


PARCEL_COPPICE_METADATA_DROP = """
DROP TRIGGER IF EXISTS parcel_coppice_metadata_insert;
DROP TRIGGER IF EXISTS parcel_coppice_metadata_update;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_insert;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_update;
DROP TRIGGER IF EXISTS eclass_coppice_metadata_update;
DROP TRIGGER IF EXISTS eclass_highforest_metadata_update;
"""

PARCEL_COPPICE_METADATA_TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS eclass_coppice_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 1
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NULL OR p.standards_per_ha IS NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS eclass_highforest_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 0
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NOT NULL OR p.standards_per_ha IS NOT NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_migrate_preserved_trees_to_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparcel",
            name="cutting_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="intervention_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="standards_per_ha",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="cutting_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="intervention_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="standards_per_ha",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            PARCEL_COPPICE_METADATA_DROP + PARCEL_COPPICE_METADATA_TRIGGERS,
            reverse_sql=PARCEL_COPPICE_METADATA_DROP,
        ),
    ]
