# Generated by Django 6.0.4 on 2026-07-21 16:49

from datetime import date as date_type

from django.db import migrations


PRESERVED_HISTORY_SURVEY_NAME = 'Alberi da preservare - storico'
PRESERVED_LEGACY_UNKNOWN_DATE = date_type(1970, 1, 1)


def assert_legacy_preserved_rows_migrated(apps, schema_editor):
    """Abort before dropping legacy PAI rows if Release 1 did not migrate them."""
    TreePreserved = apps.get_model('base', 'TreePreserved')
    TreeSample = apps.get_model('base', 'TreeSample')
    Survey = apps.get_model('base', 'Survey')

    legacy_rows = (
        TreePreserved.objects
        .order_by('id')
        .values('id', 'tree_id', 'parcel_id', 'number', 'date')
    )
    if not legacy_rows.exists():
        return

    try:
        survey = Survey.objects.get(name=PRESERVED_HISTORY_SURVEY_NAME)
    except Survey.DoesNotExist as exc:
        raise RuntimeError(
            'Cannot drop TreePreserved: migrated preserved-tree history survey '
            f'{PRESERVED_HISTORY_SURVEY_NAME!r} does not exist.'
        ) from exc

    missing = []
    for row in legacy_rows:
        sample_date = row['date'] or PRESERVED_LEGACY_UNKNOWN_DATE
        if not TreeSample.objects.filter(
                sample__survey=survey,
                sample__sample_area__isnull=True,
                sample__date=sample_date,
                tree_id=row['tree_id'],
                parcel_id=row['parcel_id'],
                preserved_number=row['number'],
                number=row['number'],
                shoot=0,
        ).exists():
            missing.append(row['id'])
            if len(missing) >= 20:
                break

    if missing:
        raise RuntimeError(
            'Cannot drop TreePreserved: legacy rows without migrated '
            'TreeSample rows: ' + ', '.join(str(pk) for pk in missing)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_historicalparcel_cutting_plan_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assert_legacy_preserved_rows_migrated,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="tree",
            name="acc_m",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="lon",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="parcel",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="preserved",
        ),
        migrations.DeleteModel(
            name="TreePreserved",
        ),
    ]
