# Generated by Django 6.0.4 on 2026-07-22 21:00

from django.db import migrations, models


TREE_SAMPLE_INVARIANT_TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS tree_sample_structured_parcel_insert
BEFORE INSERT ON base_treesample
FOR EACH ROW
WHEN EXISTS (
    SELECT 1
    FROM base_sample AS sample
    JOIN base_samplearea AS area ON area.id = sample.sample_area_id
    WHERE sample.id = NEW.sample_id
      AND area.parcel_id != NEW.parcel_id
)
BEGIN
    SELECT RAISE(ABORT, 'tree_sample parcel mismatch');
END;

CREATE TRIGGER IF NOT EXISTS tree_sample_structured_parcel_update
BEFORE UPDATE OF sample_id, parcel_id ON base_treesample
FOR EACH ROW
WHEN EXISTS (
    SELECT 1
    FROM base_sample AS sample
    JOIN base_samplearea AS area ON area.id = sample.sample_area_id
    WHERE sample.id = NEW.sample_id
      AND area.parcel_id != NEW.parcel_id
)
BEGIN
    SELECT RAISE(ABORT, 'tree_sample parcel mismatch');
END;

CREATE TRIGGER IF NOT EXISTS sample_tree_sample_parcel_update
BEFORE UPDATE OF sample_area_id ON base_sample
FOR EACH ROW
WHEN NEW.sample_area_id IS NOT NULL AND EXISTS (
    SELECT 1
    FROM base_treesample AS tree_sample
    JOIN base_samplearea AS area ON area.id = NEW.sample_area_id
    WHERE tree_sample.sample_id = NEW.id
      AND tree_sample.parcel_id != area.parcel_id
)
BEGIN
    SELECT RAISE(ABORT, 'tree_sample parcel mismatch');
END;

CREATE TRIGGER IF NOT EXISTS sample_area_tree_sample_parcel_update
BEFORE UPDATE OF parcel_id ON base_samplearea
FOR EACH ROW
WHEN EXISTS (
    SELECT 1
    FROM base_sample AS sample
    JOIN base_treesample AS tree_sample
      ON tree_sample.sample_id = sample.id
    WHERE sample.sample_area_id = NEW.id
      AND tree_sample.parcel_id != NEW.parcel_id
)
BEGIN
    SELECT RAISE(ABORT, 'tree_sample parcel mismatch');
END;

CREATE TRIGGER IF NOT EXISTS tree_sample_pai_identity_insert
BEFORE INSERT ON base_treesample
FOR EACH ROW
WHEN NEW.preserved_number IS NOT NULL AND EXISTS (
    SELECT 1
    FROM base_treesample AS existing
    WHERE existing.parcel_id = NEW.parcel_id
      AND existing.preserved_number = NEW.preserved_number
      AND existing.tree_id != NEW.tree_id
)
BEGIN
    SELECT RAISE(ABORT, 'preserved tree identity mismatch');
END;

CREATE TRIGGER IF NOT EXISTS tree_sample_pai_identity_update
BEFORE UPDATE OF parcel_id, preserved_number, tree_id ON base_treesample
FOR EACH ROW
WHEN NEW.preserved_number IS NOT NULL AND EXISTS (
    SELECT 1
    FROM base_treesample AS existing
    WHERE existing.parcel_id = NEW.parcel_id
      AND existing.preserved_number = NEW.preserved_number
      AND existing.tree_id != NEW.tree_id
      AND existing.id != NEW.id
)
BEGIN
    SELECT RAISE(ABORT, 'preserved tree identity mismatch');
END;
"""


TREE_SAMPLE_INVARIANT_TRIGGERS_DROP = """
DROP TRIGGER IF EXISTS tree_sample_structured_parcel_insert;
DROP TRIGGER IF EXISTS tree_sample_structured_parcel_update;
DROP TRIGGER IF EXISTS sample_tree_sample_parcel_update;
DROP TRIGGER IF EXISTS sample_area_tree_sample_parcel_update;
DROP TRIGGER IF EXISTS tree_sample_pai_identity_insert;
DROP TRIGGER IF EXISTS tree_sample_pai_identity_update;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_release2_drop_legacy_tree_state"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__isnull", True), ("lon__isnull", True)),
                    models.Q(("lat__isnull", False), ("lon__isnull", False)),
                    _connector="OR",
                ),
                name="tree_mark_lat_lon_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="tree_mark_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lon__isnull", True),
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    _connector="OR",
                ),
                name="tree_mark_lon_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acc_m__isnull", True), ("acc_m__gte", 0), _connector="OR"
                ),
                name="tree_mark_acc_m_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__isnull", True), ("lon__isnull", True)),
                    models.Q(("lat__isnull", False), ("lon__isnull", False)),
                    _connector="OR",
                ),
                name="tree_sample_lat_lon_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="tree_sample_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lon__isnull", True),
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    _connector="OR",
                ),
                name="tree_sample_lon_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="treesample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acc_m__isnull", True), ("acc_m__gte", 0), _connector="OR"
                ),
                name="tree_sample_acc_m_nonnegative",
            ),
        ),
        migrations.RunSQL(
            TREE_SAMPLE_INVARIANT_TRIGGERS,
            reverse_sql=TREE_SAMPLE_INVARIANT_TRIGGERS_DROP,
        ),
    ]
