# Generated by Django 6.0.4 on 2026-07-25 14:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


DEFAULT_OBSERVATION_CATEGORIES = (
    ('fitosanitario', 10),
    ('viabilità', 20),
    ('rifiuti', 30),
)


def seed_observation_categories(apps, schema_editor):
    ObservationCategory = apps.get_model('base', 'ObservationCategory')
    for name, sort_order in DEFAULT_OBSERVATION_CATEGORIES:
        ObservationCategory.objects.update_or_create(
            name=name,
            defaults={'sort_order': sort_order, 'active': True},
        )


def unseed_observation_categories(apps, schema_editor):
    ObservationCategory = apps.get_model('base', 'ObservationCategory')
    ObservationCategory.objects.filter(
        name__in=[name for name, _sort_order in DEFAULT_OBSERVATION_CATEGORIES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_tree_observation_invariants"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "categoria di osservazioni",
                "verbose_name_plural": "categorie di osservazioni",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalObservationCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical categoria di osservazioni",
                "verbose_name_plural": "historical categorie di osservazioni",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(
            seed_observation_categories,
            reverse_code=unseed_observation_categories,
        ),
    ]
