# Generated by Django 6.0.4 on 2026-07-25 15:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_observationcategory_historicalobservationcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalObservation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("date", models.DateField()),
                ("text", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("acc_m", models.IntegerField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("upload_session_id", models.CharField(blank=True, max_length=64)),
                ("client_record_id", models.CharField(blank=True, max_length=100)),
                (
                    "import_fingerprint",
                    models.CharField(blank=True, max_length=67, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical osservazione",
                "verbose_name_plural": "historical osservazioni",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("text", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("acc_m", models.IntegerField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("upload_session_id", models.CharField(blank=True, max_length=64)),
                ("client_record_id", models.CharField(blank=True, max_length=100)),
                (
                    "import_fingerprint",
                    models.CharField(blank=True, max_length=67, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "osservazione",
                "verbose_name_plural": "osservazioni",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ObservationCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.observationcategory",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="base.observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria osservazione",
                "verbose_name_plural": "categorie osservazioni",
                "unique_together": {("observation", "category")},
            },
        ),
        migrations.AddField(
            model_name="observation",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="observations",
                through="base.ObservationCategoryAssignment",
                to="base.observationcategory",
            ),
        ),
        migrations.CreateModel(
            name="ObservationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500, unique=True)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("width_px", models.PositiveIntegerField(blank=True, null=True)),
                ("height_px", models.PositiveIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="base.observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto osservazione",
                "verbose_name_plural": "foto osservazioni",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("import_fingerprint__isnull", False),
                    models.Q(("import_fingerprint", ""), _negated=True),
                ),
                fields=("import_fingerprint",),
                name="uniq_observation_import_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__isnull", True), ("lon__isnull", True)),
                    models.Q(("lat__isnull", False), ("lon__isnull", False)),
                    _connector="OR",
                ),
                name="observation_lat_lon_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="observation_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lon__isnull", True),
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    _connector="OR",
                ),
                name="observation_lon_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acc_m__isnull", True), ("acc_m__gte", 0), _connector="OR"
                ),
                name="observation_acc_m_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gte", 0)),
                name="observation_photo_size_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width_px__isnull", True), ("width_px__gt", 0), _connector="OR"
                ),
                name="observation_photo_width_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height_px__isnull", True), ("height_px__gt", 0), _connector="OR"
                ),
                name="observation_photo_height_positive",
            ),
        ),
    ]
