# Generated by Django 6.0.4 on 2026-07-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_historicalobservation_observation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalobservation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.region",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="base.region",
            ),
        ),
    ]
