# Generated by Codex on 2026-07-29

from django.db import migrations, models


HARVEST_TRIGGER_DROP = """
DROP TRIGGER IF EXISTS harvest_region_xor_parcel_insert;
DROP TRIGGER IF EXISTS harvest_region_xor_parcel_update;
DROP TRIGGER IF EXISTS harvest_parcel_consistency_insert;
DROP TRIGGER IF EXISTS harvest_parcel_consistency_update;
DROP TRIGGER IF EXISTS harvest_flags_consistency_insert;
DROP TRIGGER IF EXISTS harvest_flags_consistency_update;
"""

HARVEST_TRIGGER_CREATE = """
CREATE TRIGGER IF NOT EXISTS harvest_region_xor_parcel_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN (NEW.region_id IS NULL) = (NEW.parcel_id IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'harvest: exactly one of region or parcel must be set');
END;

CREATE TRIGGER IF NOT EXISTS harvest_region_xor_parcel_update
BEFORE UPDATE OF region_id, parcel_id ON prelievi_harvest
FOR EACH ROW
WHEN (NEW.region_id IS NULL) = (NEW.parcel_id IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'harvest: exactly one of region or parcel must be set');
END;

CREATE TRIGGER IF NOT EXISTS harvest_parcel_consistency_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND (
        (NEW.parcel_id IS NOT NULL AND (
            hpi.parcel_id = NEW.parcel_id
            OR hpi.region_id = (SELECT region_id FROM base_parcel WHERE id = NEW.parcel_id)))
        OR (NEW.parcel_id IS NULL AND hpi.region_id = NEW.region_id)
      )
)
BEGIN
    SELECT RAISE(ABORT, 'harvest.parcel/region does not match linked harvest_plan_item');
END;

CREATE TRIGGER IF NOT EXISTS harvest_parcel_consistency_update
BEFORE UPDATE OF parcel_id, region_id, harvest_plan_item_id ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND (
        (NEW.parcel_id IS NOT NULL AND (
            hpi.parcel_id = NEW.parcel_id
            OR hpi.region_id = (SELECT region_id FROM base_parcel WHERE id = NEW.parcel_id)))
        OR (NEW.parcel_id IS NULL AND hpi.region_id = NEW.region_id)
      )
)
BEGIN
    SELECT RAISE(ABORT, 'harvest.parcel/region does not match linked harvest_plan_item');
END;

CREATE TRIGGER IF NOT EXISTS harvest_flags_consistency_insert
BEFORE INSERT ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND hpi.damaged   = NEW.damaged
      AND hpi.unhealthy = NEW.unhealthy
      AND hpi.psr       = NEW.psr
)
BEGIN
    SELECT RAISE(ABORT, 'harvest flags must match linked harvest_plan_item flags');
END;

CREATE TRIGGER IF NOT EXISTS harvest_flags_consistency_update
BEFORE UPDATE OF damaged, unhealthy, psr, harvest_plan_item_id ON prelievi_harvest
FOR EACH ROW
WHEN NEW.harvest_plan_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM base_harvestplanitem AS hpi
    WHERE hpi.id = NEW.harvest_plan_item_id
      AND hpi.damaged   = NEW.damaged
      AND hpi.unhealthy = NEW.unhealthy
      AND hpi.psr       = NEW.psr
)
BEGIN
    SELECT RAISE(ABORT, 'harvest flags must match linked harvest_plan_item flags');
END;
"""

PARCEL_COPPICE_METADATA_DROP = """
DROP TRIGGER IF EXISTS parcel_coppice_metadata_insert;
DROP TRIGGER IF EXISTS parcel_coppice_metadata_update;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_insert;
DROP TRIGGER IF EXISTS parcel_highforest_metadata_update;
DROP TRIGGER IF EXISTS eclass_coppice_metadata_update;
DROP TRIGGER IF EXISTS eclass_highforest_metadata_update;
"""

PARCEL_COPPICE_METADATA_TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_coppice_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 1
)
AND (NEW.intervention_interval IS NULL OR NEW.standards_per_ha IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_insert
BEFORE INSERT ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS parcel_highforest_metadata_update
BEFORE UPDATE OF eclass_id, intervention_interval, standards_per_ha ON base_parcel
FOR EACH ROW
WHEN EXISTS (
    SELECT 1 FROM base_eclass e
    WHERE e.id = NEW.eclass_id AND e.coppice = 0
)
AND (NEW.intervention_interval IS NOT NULL OR NEW.standards_per_ha IS NOT NULL)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;

CREATE TRIGGER IF NOT EXISTS eclass_coppice_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 1
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NULL OR p.standards_per_ha IS NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'coppice parcel requires interval and standards');
END;

CREATE TRIGGER IF NOT EXISTS eclass_highforest_metadata_update
BEFORE UPDATE OF coppice ON base_eclass
FOR EACH ROW
WHEN NEW.coppice = 0
AND EXISTS (
    SELECT 1 FROM base_parcel p
    WHERE p.eclass_id = NEW.id
      AND (p.intervention_interval IS NOT NULL OR p.standards_per_ha IS NOT NULL)
)
BEGIN
    SELECT RAISE(ABORT, 'high-forest parcel cannot have coppice metadata');
END;
"""

TRIGGER_DROP = HARVEST_TRIGGER_DROP + PARCEL_COPPICE_METADATA_DROP
TRIGGER_CREATE = PARCEL_COPPICE_METADATA_TRIGGERS + HARVEST_TRIGGER_CREATE

DEFAULT_HARVEST_MECHANISM = 'Strascico con trattori'


def seed_harvest_mechanism(apps, schema_editor):
    Parcel = apps.get_model('base', 'Parcel')
    Parcel.objects.filter(harvest_mechanism='').update(
        harvest_mechanism=DEFAULT_HARVEST_MECHANISM,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_historicalobservation_region_observation_region'),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_DROP, reverse_sql=TRIGGER_CREATE),
        migrations.AddField(
            model_name='historicalparcel',
            name='harvest_mechanism',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parcel',
            name='harvest_mechanism',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(
            seed_harvest_mechanism,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(TRIGGER_CREATE, reverse_sql=TRIGGER_DROP),
    ]
