# Generated by Django 6.0.4 on 2026-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_parcel_harvest_mechanism"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationphoto",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observationphoto",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observationphoto",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__isnull", True), ("lon__isnull", True)),
                    models.Q(("lat__isnull", False), ("lon__isnull", False)),
                    _connector="OR",
                ),
                name="observation_photo_lat_lon_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="observation_photo_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lon__isnull", True),
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    _connector="OR",
                ),
                name="observation_photo_lon_range",
            ),
        ),
    ]
