# Generated by Django 6.0.4 on 2026-08-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_refresh_mark_tree_digest_schema"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="harvesttransition",
            unique_together=set(),
        ),
    ]
