# Generated by Django 6.0.4 on 2026-08-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_harvesttransition_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvesttransition",
            name="harvest_plan_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="base.harvestplanitem",
            ),
        ),
    ]
