# Generated by Django 6.0.4 on 2026-08-08 20:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_merge_cascade_and_tree_position_digests"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="diameter_class_mode",
            field=models.CharField(default="centered", max_length=20),
        ),
        migrations.CreateModel(
            name="HistoricalSiteSettings",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, editable=False
                    ),
                ),
                ("default_landing_page", models.CharField(blank=True, max_length=255)),
                (
                    "diameter_class_mode",
                    models.CharField(default="centered", max_length=20),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical impostazioni sito",
                "verbose_name_plural": "historical impostazioni sito",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
