# Generated by Django 6.0.4 on 2026-08-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_sitesettings_diameter_class_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treemark",
            name="h_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("h_m__isnull", False), ("h_measured", False), _connector="OR"
                ),
                name="tree_mark_h_measured_false_without_h_m",
            ),
        ),
        migrations.AddConstraint(
            model_name="treemark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("h_m__isnull", False),
                    models.Q(("volume_m3__isnull", True), ("mass_q__isnull", True)),
                    _connector="OR",
                ),
                name="tree_mark_no_derived_values_without_h_m",
            ),
        ),
    ]
