"""Generate build/upload-config.js from secrets/upload_config.json.

Writes a tiny JS file exposing UPLOAD_TOKEN as a global, loaded by
index.html before upload.js. The token is visible to anyone who can
fetch the PWA bundle — see the spec for the explicit risk tradeoff.
The file is regenerated on every `make build` so a stale copy cannot
survive a token rotation.

The upload base URL is intentionally NOT carried here: uploadSession()
posts to the relative path /upload, which is same-origin by construction
(production: Apache ProxyPass; local dev: tools/local-proxy.py).
"""

import json
import sys


HEADER = (
    "// AUTOGENERATED by tools/build_upload_config.py. Do not edit.\n"
    "// Source: ipso/secrets/upload_config.json (gitignored).\n"
    "'use strict';\n"
)


def main(argv):
    if len(argv) != 3:
        print(
            "usage: build_upload_config.py <secrets.json> <out.js>",
            file=sys.stderr,
        )
        return 2
    with open(argv[1], "r", encoding="utf-8") as fh:
        cfg = json.load(fh)
    token = cfg["token"]
    with open(argv[2], "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write("const UPLOAD_TOKEN = " + json.dumps(token) + ";\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
