# Generated by Django 6.0.4 on 2026-05-24 20:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Harvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("record1", models.IntegerField(blank=True, null=True)),
                ("record2", models.IntegerField(blank=True, null=True)),
                ("mass_q", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volume_m3",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Computed at write time: SUM(mass_q × pct/100 / species.density).",
                        max_digits=10,
                    ),
                ),
                ("damaged", models.BooleanField(default=False)),
                ("unhealthy", models.BooleanField(default=False)),
                ("psr", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.crew"
                    ),
                ),
                (
                    "harvest_plan_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="harvests",
                        to="base.harvestplanitem",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.parcel"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "operazione di prelievo",
                "verbose_name_plural": "operazioni di prelievo",
            },
        ),
        migrations.CreateModel(
            name="HistoricalHarvest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("date", models.DateField()),
                ("record1", models.IntegerField(blank=True, null=True)),
                ("record2", models.IntegerField(blank=True, null=True)),
                ("mass_q", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volume_m3",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Computed at write time: SUM(mass_q × pct/100 / species.density).",
                        max_digits=10,
                    ),
                ),
                ("damaged", models.BooleanField(default=False)),
                ("unhealthy", models.BooleanField(default=False)),
                ("psr", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.crew",
                    ),
                ),
                (
                    "harvest_plan_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.harvestplanitem",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.parcel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical operazione di prelievo",
                "verbose_name_plural": "historical operazioni di prelievo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HarvestSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.IntegerField()),
                (
                    "harvest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prelievi.harvest",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.species"
                    ),
                ),
            ],
            options={
                "verbose_name": "specie prelievo",
                "verbose_name_plural": "specie prelievo",
                "unique_together": {("harvest", "species")},
            },
        ),
        migrations.CreateModel(
            name="HarvestTractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.IntegerField()),
                (
                    "harvest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prelievi.harvest",
                    ),
                ),
                (
                    "tractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.tractor"
                    ),
                ),
            ],
            options={
                "verbose_name": "trattore prelievo",
                "verbose_name_plural": "trattori prelievo",
                "unique_together": {("harvest", "tractor")},
            },
        ),
    ]
