# Generated by Django 6.0.4 on 2026-06-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_triggers"),
        ("prelievi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvest",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="harvests",
                to="base.region",
            ),
        ),
        migrations.AddField(
            model_name="historicalharvest",
            name="region",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.region",
            ),
        ),
        migrations.AlterField(
            model_name="harvest",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.parcel",
            ),
        ),
    ]
