# Generated by Django 6.0.4 on 2026-07-11 00:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipso", "0002_ipsoupload_record_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ipsoupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="HistoricalIpsoUpload",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("mode", models.CharField(max_length=32)),
                ("schema_version", models.IntegerField()),
                ("reference_version", models.CharField(blank=True, max_length=100)),
                ("work_package_id", models.CharField(blank=True, max_length=100)),
                ("operator", models.CharField(blank=True, max_length=100)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "record_date",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("checksum", models.CharField(max_length=64)),
                ("inbox_path", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("imported", "imported"),
                            ("rejected", "rejected"),
                            ("conflict", "conflict"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("error_summary", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ipso upload",
                "verbose_name_plural": "historical ipso uploads",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
