# Generated by Django 6.0.4 on 2026-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipso", "0003_ipsoupload_updated_at_historicalipsoupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalipsoupload",
            name="mode",
            field=models.CharField(
                choices=[
                    ("martellate", "Martellate"),
                    ("samples", "Rilevamenti predefiniti"),
                    ("free_survey", "Rilevamenti liberi"),
                    ("observations", "Osservazioni"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalipsoupload",
            name="state",
            field=models.CharField(
                choices=[
                    ("received", "Da importare"),
                    ("imported", "Importato"),
                    ("rejected", "Rifiutato"),
                    ("conflict", "Conflitto"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalipsoupload",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("harvest_plan_item", "Voce di piano"),
                    ("survey", "Rilevamento"),
                    ("observations", "Osservazioni"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ipsoupload",
            name="mode",
            field=models.CharField(
                choices=[
                    ("martellate", "Martellate"),
                    ("samples", "Rilevamenti predefiniti"),
                    ("free_survey", "Rilevamenti liberi"),
                    ("observations", "Osservazioni"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ipsoupload",
            name="state",
            field=models.CharField(
                choices=[
                    ("received", "Da importare"),
                    ("imported", "Importato"),
                    ("rejected", "Rifiutato"),
                    ("conflict", "Conflitto"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ipsoupload",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("harvest_plan_item", "Voce di piano"),
                    ("survey", "Rilevamento"),
                    ("observations", "Osservazioni"),
                ],
                max_length=50,
            ),
        ),
    ]
